### ISSUE TITLE
Allow tokens/secrets to be specified as environment variables

### ISSUE THREAD

**Issue by trondhindenes** [marcells/node-build-monitor#102]
awesome project! My only gripe is that the config model requires that a config file with secrets is baked into the docker image, which we try to avoid.
It would be awesome if values in the config.json file could be configed with references to envvars (for example)
```
{
  "name": "Jenkins",
  "configuration": {
    "url": "http://jenkins-server:8080",
    "username": "jenkins_username",
    "password": "${envvarpassword}",

  }
}
```
For now we'll have to build our own image to inject secrets at run-time instead of build-time.

**Comment by marcells** [comment]
Good idea. I'll think about it and try to implement it as a general solution.

**Comment by marcells** [comment]
Implemented in https://github.com/marcells/node-build-monitor/releases/tag/v0.9.36.
Please check the `Readme.md`. The variable expansion feature is disabled by default.

Let me know, if anything doesn't work.

**Comment by trondhindenes** [comment]
awesome!
