### ISSUE TITLE
Visual Studio Team Services support

### ISSUE THREAD

**Issue by NihalSh** [marcells/node-build-monitor#105]
I get an error when trying to use Visual Studio Team Services configuration as mentioned in the README. It gives me the following error. 
```
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = unset (Default: 1)
node-build-monitor is starting...
module.js:540
    throw err;
    ^

Error: Cannot find module './services/VSTSRest'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nsh/projects/node-build-monitor/app/app.js:96:24)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```
Is VSTS support removed in the latest version?

**Comment by marcells** [comment]
Please check your configuration. It looks like node-build-monitor tries to load the service 'VSTSRest', which does not exist.

**Comment by NihalSh** [comment]
I checked the configuration. It is in the same format as the one given in [documentation](https://github.com/marcells/node-build-monitor#visual-studio-team-services).
```
{
  "name": "VSTSRest",
  "configuration": {
    "collection": "collection",
    "accountname": "account",
    "pat": "personalaccesstoken",
    "queryparams" : "&branchName=refs/heads/develop&$top=10&maxBuildsPerDefinition=1"
  }
}
```
Its giving this error because the file `app/services/VSTSRest.js` is missing. I checked the codebase too and that file is missing. I can make a pull request to fix it, if it is an issue. Am I missing something?

**Comment by marcells** [comment]
Oh, you're right. Looks like an issue in the docs.

Please try to use Tfs, instead of VSTSRest as the name and let me know, if it's working for you.

**Comment by NihalSh** [comment]
Now I get the following error.
```
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = unset (Default: 1)
node-build-monitor is starting...
15:10:27 | Check for builds...
node-build-monitor 0.9.37 is listening on port 3000...
/home/nsh/projects/node-build-monitor/app/services/Tfs.js:29
            for (var i = 0; i < body.value.length; i++) {
                                           ^

TypeError: Cannot read property 'length' of undefined
    at forEachResult (/home/nsh/projects/node-build-monitor/app/services/Tfs.js:29:44)
    at /home/nsh/projects/node-build-monitor/app/services/Tfs.js:81:17
    at Request._callback (/home/nsh/projects/node-build-monitor/app/requests.js:23:11)
    at Request.self.callback (/home/nsh/projects/node-build-monitor/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/nsh/projects/node-build-monitor/node_modules/request/request.js:1163:10)    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/nsh/projects/node-build-monitor/node_modules/request/request.js:1085:12)
```

**Comment by marcells** [comment]
Hm, could you try, what result you get, when you query the following url (Headers: Accept: 'application/json') with e.g. Postman:

`'https://' + pat + '@' + accountname + '.visualstudio.com/' + accountname + '/_apis/build/builds?api-version=4.1-preview&branchName=refs/heads/develop&$top=10&maxBuildsPerDefinition=1`

Please replace the variables according to your configuration.

**Comment by NihalSh** [comment]
I tried that and the response I get is an HTML page for sign in. Status `203 Non-Authoritative Information`.

**Comment by marcells** [comment]
It looks like your accesstoken hasn't the correct permissions to query the builds. You have to check that. If the url from above returns results, then it should work.

**Comment by NihalSh** [comment]
I wrote my own implementation of the service for VSTSRest. The URL I have used is similar but authentication token is passed in the header as BasicAuth. The URL is given below:
```js
`https://${instance}.visualstudio.com/DefaultCollection/${project}/_apis/build/builds?api-version=2.0${params}`
```
Can I make a pull request for adding it to the codebase?

**Comment by marcells** [comment]
Sure, just modify the existing service. Thank you.

The configuration parameters don't change?

**Comment by NihalSh** [comment]
The configuration parameters are a bit different. I had to add a few extra configuration parameters to make it work.

**Comment by NihalSh** [comment]
I will make the pull request after I have documented the code.

**Comment by marcells** [comment]
Okay. Thank you. I'll take a look at it then.
