### ISSUE TITLE
VSTS Release Support

### ISSUE THREAD

**Issue by xAaeEx** [marcells/node-build-monitor#108]
Hi,

is it possible to get support for the releases too? I know there is a REST api for that in the docs of ms.
It would be awesome to get those informations in the dashboard.
[https://docs.microsoft.com/en-us/rest/api/vsts/release/releases/list](https://docs.microsoft.com/en-us/rest/api/vsts/release/releases/list)

**Comment by marcells** [comment]
We already had that topic in issue #51. Feel free to implement it. I accept pullover requests. 😉

You could take a look at the tfs service (Visual Studio Team Services and on-premise). The implementation should be similar.

**Comment by xAaeEx** [comment]
I added support for that and created a pull request [https://github.com/marcells/node-build-monitor/pull/109](https://github.com/marcells/node-build-monitor/pull/109)

**Comment by xAaeEx** [comment]
@marcells sorry I saw your comment too late and added the file as **VstsReleases**

**Comment by marcells** [comment]
Fixed in PR #109.
