### ISSUE TITLE
What about extensions?

### ISSUE THREAD

**Issue by jlouazel** [marcells/node-build-monitor#11]
Hi @marcells.

In the description of your repository, you said that your project can be easily extended.
I'm planning to contribute for GitlabCI and I want some advices. Do you have some code that facilitate an integration of a new service? How can I start a new integration?

Thanks

**Comment by marcells** [comment]
Cool, @jlouazel, thank you.

Just take a look at the existing services in the services directory of the repository, if you need a template.

In your case create a file named `Gitlab.js` in this directory, and implement the `configure()` and `check()` methods, like the other services do it. It will be registered automatically and can be configured in the central `config.json` (the `configuration` key will be called in the `configure()` method of your service).

```
...,
"services": [
    {
      "name": "Gitlab",
      "configuration": {
        "someParam": "someValue"
      }
    }, ...
  ],
...
```

If you need more information or some help, then feel free to ask!

Regards
Marcell
