### ISSUE TITLE
Troubles connecting to TFS 2018 Update 1

### ISSUE THREAD

**Issue by search8** [marcells/node-build-monitor#110]
Hi 
I'm trying to connect to TFS 2018 (Update 1) (which from my understanding shouldn't be much different than TFS 2017) but keep getting the following error:

```
PS C:\BuildMonitor> .\node-build-monitor-win.exe
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = unset (Default: 1)
node-build-monitor is starting...
7:20:17 AM | Check for builds...
node-build-monitor 0.9.38 is listening on port 3000...
C:\snapshot\node-build-monitor\app\services\Tfs2015.js:27
            for (var i = 0; i < body.value.length; i++) {
                                          ^

TypeError: Cannot read property 'length' of undefined
    at forEachResult (C:\snapshot\node-build-monitor\app\services\Tfs2015.js:27:43)
    at C:\snapshot\node-build-monitor\app\services\Tfs2015.js:82:17
    at Request._callback (C:\snapshot\node-build-monitor\app\requests.js:23:11)
    at Request.init.self.callback (C:\snapshot\node-build-monitor\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\snapshot\node-build-monitor\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\snapshot\node-build-monitor\node_modules\request\request.js:1085:12)
```

From the error message it would seem my configuration is wrong, but I don't see what I'm missing:

```
{
  "monitor": {
    "interval": 30000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "expandEnvironmentVariables": false,
    "debug": true
  },
  "services": [
    {
  "name": "Tfs2015",
  "configuration": {
    "url": "https://<domain>/DefaultCollection/<teamproject>",
	  "username": "<domain\user>",
    "password": "<token with build read access>"
  }
}
  ]
}
```

I've set the access right accordingly and I'm able to connect with other build monitors. However I like this one better than the others I have found why I would really like to get it to work. Any one else having issues with TFS 2018 Update 1 or what am I missing?

Thanks,
Serge

**Comment by marcells** [comment]
Hi,

you could try the `Tfs` Service (`Tfs2015` will be deprecated and removed in future). It was implemented recently by @NihalSh who had issues, too. Take a look at the conversion in issue #105.

Use "https://{domain}/{collection}" as the instance setting.
See the full docs for this service [here](https://github.com/marcells/node-build-monitor#visual-studio-team-services-and-team-foundation-server).

**Comment by search8** [comment]
Hi,

thanks for the answer, not sure how I missed that! I changed the config now but I'm getting a different error now:

```
An error occured when fetching builds for the following configuration:
----------------------------------------------------------------------
{ project: '<teamprojectname>',
  instance: 'https://<domain>/DefaultCollection/',
  username: '<domain\user>',
  pat: 'sx4dcardfyas45fd65sda46f54as6f4sdf65sda4dgxc4yq' }
----------------------------------------------------------------------

{ Error: getaddrinfo ENOTFOUND https https:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'https',
  host: 'https',
  port: 443 }
**********************************************************************
```

The config I changed to this:

{
  "monitor": {
    "interval": 30000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "expandEnvironmentVariables": false,
    "debug": true
  },
  "services": [
    {
  "name": "Tfs",
  "configuration": {
	  "project": "<teamprojectname>",
    "instance": "https://<domain>/DefaultCollection/",
	  "username": "<domain\user>",
    "pat": "sx4dcardfyas45fd65sda46f54as6f4sdf65sda4dgxc4yq"
  }
}
  ]
}

I tried to mess around with the instance name a little bit (with and without http/https, pointing directly to the server). However the error remains the same.

**Comment by search8** [comment]
I had a closer look at issue #105. When I connect with postman using BasicAuth as described with the following url it works:

https://${instance}.<tfsdomain>/DefaultCollection/${project}/_apis/build/builds?api-version=2.0${params}

So I don't know what the issue might be. Seems nodejs related and I don't know nodejs at all unfortunately.

**Comment by marcells** [comment]
For the domain\user, you have to escape \ with another \. So you have to write domain\\user.

Does that change something?

**Comment by search8** [comment]
No unfortunately not, I had already tried that as well. When I connected with Postman I didn't even specify the domain. So I had tried with and without and also with one and two \. 

In fact I'm not even getting an exception right now. It just says the following:

```
An error occured when fetching builds for the following configuration:
----------------------------------------------------------------------
{ project: '<name>',
  instance: '<server>:443/DefaultCollection/',
  username: '<user>',
  pat: 'sx4dcardfyas45fd65sda46f54as6f4sdf65sda4dgxc4yq' }
----------------------------------------------------------------------

No values found
**********************************************************************
```

But I don't see what the error is.

**Comment by marcells** [comment]
Hm, you could try to compare the requests made by postman with the requests made by the build monitor by using Fiddler.

Another try would be to set the env variable NODE_TLS_REJECT_UNAUTHORIZED to 0. (Only needed if you don't have a valid certificate) 

Something has to be different. 😉

**Comment by search8** [comment]
Oh man, just had a look at the code, that helped :-) Should have done that at the beginning.
`https://${instance}/DefaultCollection/${project}/_apis/build/builds?api-version=2.0${params}`
The configuration was messed up after all. DefaultCollection is already part of the partial url and therefore can't be part of the instance. In addition I did not realize that queryparams would be a mandatory parameter. I figured that would be optional. So after I added "queryparams":"" it worked. Maybe that's something to consider for the future. It would probably help to have another column in the documentation where it's specified which parameters are mandatory and which are optional. Unless they're always all mandatory which for the Tfs service that seems to be the case.

Thanks for the help.

**Comment by search8** [comment]
Plus it would be really nice if it was possible to specify an optional api version. Because the current one is already api-version=4.1-preview and it is currently hard coded. 

Other than that it looks great. Thanks for your efforts!

**Comment by marcells** [comment]
Good to hear that it is working for you now. 👍

You're right. A hint in the docs would be good to know what's mandatory. I thought, that you have to define DefaultCollection, cause it could change. That has to be updated in the service implementation.

Changing the api version should not be allowed, cause there could be breaking changes and we want to be compatible to older tfs versions.

**Comment by search8** [comment]
True, the DefaultCollection could change.

Regarding the version I don't necessarily agree. I think an optional parameter would be great with the currently set version as fallback. That way I could use the newer api if I wanted to and you would still stay backward compatible. Now if I want to use the new api I have to fork the project and adjust it myself since it's hard coded. Doable but not ideal in my opinion.

**Comment by NihalSh** [comment]
I compared the two versions at a glance and there seems to be no significant difference at all. The only difference that could be spotted is in the URL formation and compatibility of version 2.0 with both TFS server and VSTS.

The docs for version 2.0 is at https://www.visualstudio.com/en-us/docs/integrate/api/build/builds and for version 4.1 preview is at https://docs.microsoft.com/en-us/rest/api/vsts/build/builds/list.

Did you spot any other major difference between the two which affects the usability?

**Comment by search8** [comment]
You're right. I got mixed up with the Build and Release list. There's a flag latestAttemptsOnly so I thought the api had changed because I still have troubles getting just the latest build.

When I set maxBuildsPerDefinition=1 I don't get any builds in return. When I remove the flag completely it works. Not sure why that is. Did you ever experience that problem?

Sorry for the api confusion.

**Comment by search8** [comment]
I just read that I need to specify a list of definitions as well. So I'm going to try that. 

If that's the case then maybe update your example as well. Because I just copied that and that doesn't seem to work.

`&branchName=refs/heads/develop&$top=10&maxBuildsPerDefinition=1`

Thanks.

**Comment by search8** [comment]
Ok, I just tested it. The params should look like this:

`&branchName=refs/heads/master&definitions=4,5,6,7&maxBuildsPerDefinition=1`

Turns out the Tfs service and api works just fine :-) Only the documentation could use some updating since it's pretty misleading in my opinion.

Thanks for all the help.

**Comment by NihalSh** [comment]
I have made the pull request for this already so that the URL points to the correct version. I will update the information about the usage of `maxBuildsPerDefinition` along with `definitons`. Although I do think that information is better documented in the official docs, it may very well be redundant to add the info about `maxBuildsPerDefinition` here.

**Comment by search8** [comment]
Cool, thanks. Yeah either way is fine I guess. The api documentation is pretty good. It's just that the sample as specified did not work. So either remove the maxBuildsPerDefinition or add the definitions to it.

**Comment by NihalSh** [comment]
Yeah, I realized that example was a bit misleading. The example has been updated in the pull request #111 . Thanks for pointing that out.

**Comment by marcells** [comment]
Do you know if the same informationen is valid for the TFS release api?

If yes, I will update the docs for this service, too.

**Comment by NihalSh** [comment]
For TFS release API there is no option for `branchName` and `maxBuildsPerDefinition`. Those are only for TFS build API. So the example for queryparams should be modified to avoid confusion.

**Comment by marcells** [comment]
I did update the docs and made the collection configurable (only for the Tfs service) now.

@NihalSh Could you tell me, if my changes are correct?
The commits are 696b55a1b5b48b725e735939b964202323f5cf81 and 994ec8728e93161d4ac802434581faa9d916f384.

**Comment by NihalSh** [comment]
https://github.com/marcells/node-build-monitor/commit/994ec8728e93161d4ac802434581faa9d916f384
There is no way to configure the collection in version 2.0 API, it should always be `DefaultCollection`. API 4.1-preview has removed `DefaultCollection` altogether, and there is no separate configuration for collection. If people try to configure it the API call may fail, the commit may need to be reverted.
[Builds: Version 2.0 API docs](https://www.visualstudio.com/en-us/docs/integrate/api/build/builds)
[Builds: Version 4.1-preview API docs](https://docs.microsoft.com/en-us/rest/api/vsts/build/builds/list)

https://github.com/marcells/node-build-monitor/commit/696b55a1b5b48b725e735939b964202323f5cf81
The `queryparams` example is good now. `TfsRelease` may only support VSTS, so docs may need to revised again for `instance`. The official API does not mention support for TFS server with 4.1-preview API, only VSTS is mentioned. Have you tried this with TFS server?
[Release: 4.1-preview](https://docs.microsoft.com/en-us/rest/api/vsts/release/deployments/list)

**Comment by marcells** [comment]
I wonder, how they could remove the collection parameter. On Tfs Server you can create multiple collections and e.g. give a project the same name in different collections.

Alright, thanks. No, I never tested the TfsRelease service. We need to upgrade to Tfs 2018 first, I think. In these docs I looks, like it should work.
https://www.visualstudio.com/en-us/docs/integrate/api/rm/releases

**Comment by NihalSh** [comment]
I haven't worked with Tfs Server, so can't say much on that. Maybe for API collection name would become part of the project name itself. It would depend possibly on how Tfs Server exposes the URL for each project.

In the overview section of the docs, it says the same thing for Tfs 2015 (version 2.2-preview.1). Tfs 2018 could possibly support the new version of the API. The docs are not very clear on that. Only someone running Tfs 2018 can confirm.

**Comment by marcells** [comment]
We are currently working with TFS 2017 and can modify the collection part of the URL. So I think that's a valid parameter even if it is not described in the documentation.

So, I think it should work. If someone has issues then the implementation simply has to be changed. ;-)
