### ISSUE TITLE
GitlabCI 'manual' status support

### ISSUE THREAD

**Issue by Vatrax** [marcells/node-build-monitor#118]
When pipeline is waiting for manual action it has default (gray) color.

 I suggest that it could be green, like success, but with warning.

**Comment by marcells** [comment]
I think green is misleading, cause the build could be aborted while waiting for an action.

I would propose the running color (blue). Or a new color for it.

**Comment by Vatrax** [comment]
OK, but on the other hand manual is optional step, so often builds will finish with this step.

**Comment by Vatrax** [comment]
it's 'manual'

**Comment by marcells** [comment]
Maybe we can do the following. If it's on manual state and running, then we display a blue color. And if it's in manual state and finished then we display the green color.

What do you think?

**Comment by Vatrax** [comment]
Sounds great

**Comment by marcells** [comment]
I don't have a running GitLab service.

Could you implement the change and make a PR?
