### ISSUE TITLE
node-build-monitor not installing on Mac

### ISSUE THREAD

**Issue by cisum-la** [marcells/node-build-monitor#121]
node-build-monitor not installing on Mac

I installed the Mac version but it does not appear to be a dmg and downloaded as a Text file instead.
Please clarify how to install it on a Mac.

**Comment by laughingMan** [comment]
`chmod +x node-build-monitor-macos`
`./node-build-monitor-macos &`

**Comment by marcells** [comment]
Thanks, @laughingMan. Same on Linux. I will update the docs.

**Comment by cisum-la** [comment]
Thanks for the info - it worked.

**Comment by marcells** [comment]
Added Info to readme in commit 2a2bcc608ac472970bd77df587fdb3f71303cd59.
