### ISSUE TITLE
Error: getaddrinfo ENOTFOUND https https:443

### ISSUE THREAD

**Issue by MBERoxit** [marcells/node-build-monitor#124]
I get this error trying to connect to a VSTS instance. I configured it just like described. Is this a bug?

{ Error: getaddrinfo ENOTFOUND https https:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'https',
  host: 'https',
  port: 443 
}

**Comment by marcells** [comment]
Hm, how does your config look like? You can anonymize the account name and PAT.
