### ISSUE TITLE
TeamCity Compatibility 

### ISSUE THREAD

**Issue by bstrac77** [marcells/node-build-monitor#126]
Do you know if there are any issues with the build monitor and TeamCity 2017.2.2 (build 50909)? I'm unable get my builds to display. Not sure if it's an authentication issue? I have my server configured for Basic HTTP authentication and I've successfully issued a GET to the server's API using the full URL for a specific configuration (see example below). 

http://username:password@tc-server:8111/httpAuth/app/rest/buildTypes/id:_buildConfigurationId_

Am I missing anything? Perhaps a configuration on the TC server side? This app seems to be a perfect fit for what I'm looking for. It would be great to get it working. 

Any assistance or advice would be greatly appreciated.

**Comment by bstrac77** [comment]
After more troubleshooting, it seems to only be an issue with certain builds and is most likely a problem with my TeamCity server. 

Great app! Thanks!

**Comment by marcells** [comment]
Thank you. 😉
