### ISSUE TITLE
Allow latestBuildOnly to be configured at service level

### ISSUE THREAD

**Issue by ssonger** [marcells/node-build-monitor#127]
It would be great if the "latestBuildOnly" setting could be set or overwritten at the service level. For example, we have a mix of Travis-CI and TFS builds. We set the latestBuildOnly to be true. While this works great for Travis-CI since each service is a separate project/app, for TFS we found that we only got one build back even though we included several build definitions in queryParams string. Somethign like "queryparams": "&definitions=4,5,6,7&maxBuildsPerDefinition=1" already tells TFS to return one build per definition. We can work around this by specifying a separate service for each TFS project/app but that means a fair amount of duplication since most of the other service settings remain the same.....

**Comment by marcells** [comment]
Yes, good idea. Do you mind implementing a `latestBuildOnly` configuration in the Travis service? Then you could remove it from your global configuration. I'll review and merge your PR.

**Comment by marcells** [comment]
Closed in #128.
