### ISSUE TITLE
GitlabCI not finding new builds once running

### ISSUE THREAD

**Issue by LukeFieldsend-GS** [marcells/node-build-monitor#130]
setup: 
node-build-monitor running in docker container, targeting hosted gitlab-ci

config:
`{
    "monitor": {
      "interval": 30000,
      "numberOfBuilds": 50,
      "latestBuildOnly": false,
      "sortOrder": "date",
      "expandEnvironmentVariables": false,
      "debug": true
    },
    "services": [
        {
            "name": "GitLab",
            "configuration": {
              "url": "hosted_instance_url",
              "token": "************",
              "additional_query": "&starred=true",
              "numberOfPipelinesPerProject": 1,
              "slugs": [
                {
                  "project": "GroupName/*",
                  "ref": "master"
                }
              ]
            }
          }
    ]
  }`

issue: 
config is built into a docker image and ran on aws fargate. Finding the correct number of projects when initially run and seeming to query every 30 seconds as expected. When I star projects to add them to the build monitor from the account with the configured token. I expect the new builds to appear on the next refresh.

This does not happen, but upon restarting the AWS task it picks up the new builds.

I was able to reproduce this issue running the docker image locally.

**Comment by marcells** [comment]
I took a look in the GitLab service and I see, that there is some projects state saved in [line 205](https://github.com/marcells/node-build-monitor/blob/2607c264ae5a44f01c93c7d4773d461f677acdd9/app/services/GitLab.js#L205).

I don't have a running GitLab instance here. So maybe you could remove that cache, if it is possible. Do you think you could do this?

**Comment by LukeFieldsend-GS** [comment]
Hey @marcells definitely can, I give it a go and rebuild now

**Comment by LukeFieldsend-GS** [comment]
@marcells I've got a fix for the issue and a branch ready for pull request. do I have to be invited to contribute to have permission to push the branch

**Comment by marcells** [comment]
Sure. Just make a PR. I'll review it and will merge it.

**Comment by LukeFieldsend-GS** [comment]
@marcells  no problem, https://github.com/marcells/node-build-monitor/pull/138

**Comment by LukeFieldsend-GS** [comment]
Fixed merged
