### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by nishantbakhrey** [marcells/node-build-monitor#136]
C:\node-build-monitor-master>node app/apps.js
module.js:549
 throw err;

Error: Cannot find module 'express'
       at Function.Module._resolveFilename (module.js:547:15)
       at Function.Module._load (module.js:474:25)
      .....
      .....
      .....
      .....
      .....
      .....

Can you please help me in solving this error, I'm new to this tool.

**Comment by marcells** [comment]
You have to run `npm install` first.

**Comment by marcells** [comment]
Or download the release from GitHub like described in the README.md.
