### ISSUE TITLE
How to run monitor with Travis service on Mac?

### ISSUE THREAD

**Issue by wmilton211** [marcells/node-build-monitor#155]
Trying to hook it into Travis for the last week..cant find any documentation on how to activate it, how it points to Travis with creds/no creds or URLs to your GitHub account and how to troubleshoot common problems.

**Comment by marcells** [comment]
Hi, 

please take a look at the Readme.md. All information about the general and service configuration can be found there.

Kind regards

**Comment by wmilton211** [comment]
Hi, Marcells
I appreciate you getting back so quickly. I’ve read the Readme.md exhaustively and tried to set this up approx. 7 times with not an ounce of success. I’ll just give you a quick rundown of issues for me:

-Downloaded the Mac version and unzipped it
-Put it in the Documents folder - Created a config.json (and put it in the same folder with the Mac version) with the following contents:
 {
  "monitor": {
    "interval": 30000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "errorsFirst": false,
    "expandEnvironmentVariables": false,
    "debug": true
  },
  "services": [
    {
      "name": "Travis",
      "configuration": {
        "slug": "wmilton211/gui-tests",
        "url": "http://travis-ci.org",
        "token": "is obscured here for purposes of this conversation",
        "is_enterprise": false
      }
    }
  ]

-Then I tried to execute it from my terminal, like so: Waynes-MacBook-Pro:Documents waynemilton$ node-build-monitor-macos
Which said: -bash: node-build-monitor-macos: command not found
-Opening a browser to go to localhost, of course, doesn’t work because its not running nor is it installed...

So….minor questions could be:
How do I install this? 
How do I run this?
Is the config.json written correctly? Yours looks different than mine? 
How is it connecting to Travis/GitHub to know what to display? 
Doesn’t it need a usernsme/password/token? 
Do I need my GitHub token or Travis token or Access token?
Do I need to create a personal access token with access to read builds?

So, these are the kind of issues I’m having…a tutorial for dummies (like myself) could hurt, either. Thanks for your time and effort.

**Comment by marcells** [comment]
Hi,

at first, your config is incorrect.

According to the description in the Readme it should look like:
```
...
"services": [
{
    "name": "Travis",
    "configuration": {
    "slug": "wmilton211/gui-tests",
    "url": "travis-ci.org",
    "token": "is obscured here for purposes of this conversation",
    "is_enterprise": false
}
...
```

(You can completely ignore the `url` and `is_enterprise` setting, cause it defaults to the values you want to use)

After that, please follow the steps described here: https://github.com/marcells/node-build-monitor#run-the-standalone-version-easiest-way

Kind regards
Marcell

**Comment by marcells** [comment]
Alright, thank you. I'll close the issue now.
