### ISSUE TITLE
Bitbucket Support for Team projects

### ISSUE THREAD

**Issue by donahcandia** [marcells/node-build-monitor#157]
Hi,

I am currently working on integrating node-builder-monitor with our Bitbucket repositories. Our repositories sits on a team project. Would it be a good solution to override some of the function on the Bitbucketpipeline.js or there are other ways to access the team project?

Here is our situtation: we have team projectB when we configure it on the config file it only asked for the username and apikey with the slugs. As the code only access those slugs within the username with its pipelines not within a team project.

Thank you hoping for a positive responds.

**Comment by marcells** [comment]
Hi, I don't understand your question completely. But it sounds that you could extend the existing service by your needs (don't break existing functionality).

**Comment by 030** [comment]
@donahcandia Could you review the PR?

**Comment by donahcandia** [comment]
@marcells  Sure will checked on it. Thank you.

**Comment by marcells** [comment]
Thank you. I made comments in the PR.

**Comment by 030** [comment]
@donahcandia the code has been merged. Could you test it?

**Comment by 030** [comment]
@marcells I think that this ticket could be closed

**Comment by marcells** [comment]
Yes, right. Thanks for the hint.
