### ISSUE TITLE
How to get started paragraph could be improved

### ISSUE THREAD

**Issue by 030** [marcells/node-build-monitor#159]
We only had to run:

`docker run -v ~/config.json:/build-mon/app/config.json -p 3000:3000 marcells/node-build-monitor`

to get started

Also, why does the docker-compose file contain a `build: .`? It is not needed to build it. Just mounting the config seems to be sufficient.

**Comment by marcells** [comment]
The intension of the structure of the docker container is, that you create your custom image with the config file included. After you did that you don't need to mount the config file into the container.
