### ISSUE TITLE
Clicking on bitbucket link returns forbidden URL

### ISSUE THREAD

**Issue by 030** [marcells/node-build-monitor#162]
![incorrect-url-node-screen](https://user-images.githubusercontent.com/7524528/50827196-1ef84d00-133e-11e9-9941-6b1bde3fd9da.png)

The assumption was that the project in bitbucket would open, but instead an API call is done. Could you explain how it should work?

**Comment by marcells** [comment]
It looks, like the wrong url is returned by the service. There should open a new new tab with the build details.

**Comment by NithyaAhila** [comment]
{HostUrl}/builds/browse/{PlanKey} -> works for me.
Can you explain more about your issue if it still exists.

**Comment by marcells** [comment]
@030 Can I close this issue?

**Comment by 030** [comment]
@marcells Yes that is fine. I will close it now.
