### ISSUE TITLE
Status per build pipeline item or release pipeline item

### ISSUE THREAD

**Issue by jimpouwels** [marcells/node-build-monitor#169]
Hi,

I'm using the tool for Azure devops server builds and Azure devops release builds.

However, we're interested in showing the current build status per pipeline, instead of a list of build-runs of all pipelines. 

Because now it's showing old red builds, whereas a later build was already green. 

Is there a way to do this currently?

Regards, Jim

**Comment by marcells** [comment]
Sadly I cannot answer the question, cause I did not implement the TfsRelease server. Feel free to contact the contributer or just take a look in the source code.
