### ISSUE TITLE
Crash after running for about 15 minutes

### ISSUE THREAD

**Issue by finlaybob** [marcells/node-build-monitor#178]
Using prebuilt `.\node-build-monitor-win.exe` on a Tfs (Azure DevOps) build definition
Seems to happen after about 15 minutes
```
1:16:59 PM | Check for builds...
node-build-monitor 0.9.55 is listening on port 3000...
1:17:01 PM | 88 builds found....
...
1:31:13 PM | 88 builds found....
C:\snapshot\node-build-monitor\node_modules\async\dist\async.js:955
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at C:\snapshot\node-build-monitor\node_modules\async\dist\async.js:955:32
    at C:\snapshot\node-build-monitor\node_modules\async\dist\async.js:1123:13
    at __dirname.VSTSRestBuilds.request.makeRequest (C:\snapshot\node-build-monitor\app\services\Tfs.js:394:18)
    at Request._callback (C:\snapshot\node-build-monitor\app\requests.js:52:13)
    at Request.init.self.callback (C:\snapshot\node-build-monitor\node_modules\request\request.js:185:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\snapshot\node-build-monitor\node_modules\request\request.js:881:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
```

Config as follows:
```
{
  "monitor": {
    "interval": 5000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "debug": true
  },
  "services": [
    {
      "name": "Tfs",
      "configuration": {
        "url": "https://xxx.visualstudio.com",
        "collection": "xxx",
        "project": "xxx",
        "username": "xxxx",
        "pat": "xxx",
        "queryparams": "",
        "includeQueued": true,
        "showBuildStep": true
      }
    }
  ]
}
```

**Comment by marcells** [comment]
Hm, strange. We use it for Azure DevOps server on the same way for a while and this issue never occured.

Do you have any idea what could cause this issue?

**Comment by finlaybob** [comment]
Not sure. That specific error has not happened again since that day when it did it 3 times in a row. 
I've now had it running for a good few days and not seen it.

**Comment by eichelkrauta** [comment]
I can look at this soon, but as a work around it seemed that us having the `showBuildStep` configuration as `true` was the cause for the issue. You can try setting `showBuildStep: false` in your config.json as a workaround

**Comment by meeces2911** [comment]
Whoops, looks like when a response returned from the build API wasn't one we were expecting the callback call made would break.
I've reworked all the callback calls in the buildSteps method to always return something (which they probably should have been to begin with) which should prevent this from happening.
I also added some additional logging so you can see things like 401 unauthorised errors a little more clearly in the console.
