### ISSUE TITLE
CircleCI Support

### ISSUE THREAD

**Issue by jlouazel** [marcells/node-build-monitor#18]
Hi,

Is there any project to support CircleCI soon?

Regards,

**Comment by marcells** [comment]
Currently not planned. But the Rest API looks good: https://circleci.com/docs/api.

Do you think you could implement it and make a pull request?

**Comment by jlouazel** [comment]
Yes, their API is quite good. I will try to do that this week if I can find some time to.

**Comment by maximelebastard** [comment]
See PR #186

**Comment by sverhagen** [comment]
This can probably be closed now.
