### ISSUE TITLE
HTTP/HTTPS for TfsRelease should be configurable

### ISSUE THREAD

**Issue by dreanor** [marcells/node-build-monitor#193]
The TfsRelease service currently has a hardcoded https in the url. It would be nice if it could be changed like in the Tfs service where the entire server url is configurable.

This becomes a problem if a on-premises server is only running under HTTP.

**Comment by marcells** [comment]
This is a good idea, but would be a breaking change. If you want to, you can send a PR. I think not too many people should be affected.
