### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by pascalberger** [marcells/node-build-monitor#195]
There were quite a few fixes and new services added since latest release. Would it be possible to cut a new release (to avoid needing to use latest tag of Docker image in production)?

**Comment by marcells** [comment]
Hi,

I did create a new release.

https://github.com/marcells/node-build-monitor/releases/tag/v0.9.56

Kind regards

**Comment by pascalberger** [comment]
@marcells Thank you very much. Really appreciated 👍
