### ISSUE TITLE
Support for Gitlab CI

### ISSUE THREAD

**Issue by petecoop** [marcells/node-build-monitor#2]
Support for private [Gitlab CI](https://about.gitlab.com/gitlab-ci/) servers would be great.

API documentation available [here](https://gitlab.com/gitlab-org/gitlab-ci/tree/master/doc/api)

**Comment by marcells** [comment]
I've no experience with GitLab, but I'll take a look at it soon.

Resources:
- Testing environment:
    - [Docker GitLab](https://github.com/sameersbn/docker-gitlab)
    - [Docker GitLab CI](https://github.com/sameersbn/docker-gitlab-ci)
- API
    - [API Docs](https://gitlab.com/gitlab-org/gitlab-ci/tree/master/doc/api)
    - [SO: API to request Builds](http://stackoverflow.com/a/15342142)

**Comment by marcells** [comment]
@petecoop 
I did set up a demo environment (GitLab, GitLab CI, GitLab CI Runner) and the Rest API calls to GitLab are working. But the Rest API calls to the GitLab CI server always respond with a `403 Forbidden` error. I've no idea what's the cause of the problem.

That's the url, which I tried to request. The token belongs to the admin user.
`http://gitlab-ci/api/v1/projects?private_token=h7Mf4DiaCpXC9fQRDNVP&url=http://gitlab/`

Do you think it's possible for you to implement the service by yourself and create a pull request?

**Comment by petecoop** [comment]
@marcells I'll look into it when I've got a bit of time.

Not sure what the cause of the problem you're having is but I've got a live setup that I can test with so will be much easier

**Comment by marcells** [comment]
Exactly. Thank you.

**Comment by jlouazel** [comment]
Any news about this topic guys?

**Comment by marcells** [comment]
I thought @petecoop wanted to write a plugin for GitLab CI. Maybe you find some time?

**Comment by mablae** [comment]
Hey guys, 

I am also using Gitlab CI now and want to have an awesome monitor like this :smile: 

I will look into the details and implement it, when possible. Should not be a big task since Gítlabs API pretty much follows the Travis CI API. However sadly none of the available node gitlab API client have the CI api calls implemented yet. Now I am wondering: Should I patch one of those libs first? Which one is most active? Any help on this topic? 

Thanks.

**Comment by marcells** [comment]
Hi @mablae,

you can take a look at the implementation of the Travis service. I just use a few simple rest calls via `request`. But if you want to contribute to the node Gitlab API first and then use this wrapper, feel free to do it. 

I'm fine with both approaches.

Regards
