### ISSUE TITLE
Attempting to add as new service for BuildBuddy

### ISSUE THREAD

**Issue by ktoley** [marcells/node-build-monitor#20]
What is the minimum require for a build to display?
I attempted to create a new service based on GitLab.js and while it looks like I have no problems accessing the build stats, and the console log shows the correct number of builds and projects the web site either shows the loading animation indefinitely or loads with no build tiles.

Do you happen to have an example service with a mock build which fully displays?

**Comment by marcells** [comment]
You can take a look at [GitLab.js](https://github.com/marcells/node-build-monitor/blob/master/app/services/GitLab.js) or at the other services to get some inspiration. The `Tfs.js` or `Tfs2015.js` are quite simple.
