### ISSUE TITLE
Docker container with Release 0.9.57 is missing on docker hub.

### ISSUE THREAD

**Issue by eoehen** [marcells/node-build-monitor#208]
Docker container for Release 0.9.57 is missing on docker hub.
https://hub.docker.com/r/marcells/node-build-monitor/tags

**Comment by marcells** [comment]
I think the automated builds in Docker Hub don't work from time to time. There are a few issues about that [here](https://github.com/docker/hub-feedback/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+tag+github).

You could use the `latest` tag as a temporary solution. That should be Version 0.9.57.

I hope it will work for the next release.

**Comment by marcells** [comment]
I did build and upload the docker image manually now. You can use it.
