### ISSUE TITLE
Monitors with failed configurations could log credentials

### ISSUE THREAD

**Issue by nkringle** [marcells/node-build-monitor#211]
https://github.com/marcells/node-build-monitor/blob/master/app/monitor.js#L176

As services include api credentials in their spec, when a configuration fails to load, the log statement with the configuration should either remove credentials, or have an option to disable logging for [this](https://github.com/marcells/node-build-monitor/blob/master/app/monitor.js#L176) line.

**Comment by marcells** [comment]
Good idea. I'll add a new flag to the configuration.

**Comment by marcells** [comment]
The issue is fixed. Please take a look at commit de9ced4f92f547f8b9fa41a56d8f73ad237be6a4.
