### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by nkringle** [marcells/node-build-monitor#212]
There have been a couple of additions since the latest release (0.9.57). What is the timeline for cutting a new release?

We're specifically looking at https://github.com/marcells/node-build-monitor/pull/210 and https://github.com/marcells/node-build-monitor/pull/207.

**Comment by marcells** [comment]
I'll create a new release soon.

**Comment by marcells** [comment]
Here we go: https://github.com/marcells/node-build-monitor/releases/tag/v0.9.58
