### ISSUE TITLE
Connecting With Travis-ci facing error no -4078

### ISSUE THREAD

**Issue by khan-hassan** [marcells/node-build-monitor#215]
I am running node-build-monitor manually. my config file is attached below.
I am facing error no : -4078.
Error: connect ECONNREFUSED 54.243.143.241:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '54.243.143.241',
  port: 443
}
Can you help? I think i am taking token wrong. 

```
{
  "monitor": {
    "interval": 5000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "debug": true
  },
  "services": [
    {
      "name": "Travis",
      "configuration": {
        "slug": "khan-hassan/react-test-ci",
	"token": "token here."
      }
    },
    {
      "name": "Travis",
      "configuration": {
        "slug": "khan-hassan/react-test-ci",
        "latestBuildOnly": true
      }
    }
  ]
}
```

**Comment by marcells** [comment]
Your second part in the configuration looks wrong:
```
{
      "name": "Travis",
      "configuration": {
        "slug": "khan-hassan/react-test-ci",
        "latestBuildOnly": true
      }
    }
```

Is the issue still present?
