### ISSUE TITLE
Unit test Drone Service

### ISSUE THREAD

**Issue by nkringle** [marcells/node-build-monitor#219]
The drone service is not unit tested. I think this is leading to bugs. (I keep running into a scenario where when I do not include a `branch` or `event` it does not find and builds.

**Comment by nkringle** [comment]
If I get free time this weekend I will try to submit a PR.

**Comment by nkringle** [comment]
Also, I contributed to the problem with #214 as I didn't add unit tests. ;)

**Comment by marcells** [comment]
Thank you.
