### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by wojciiii** [marcells/node-build-monitor#22]
I'm using node v4.4.7 on Ubuntu.

I get the following exception when trying to use the monitor. I configured two Jenkins jobs to be monitored in app/config.json.

3:46:37 PM | Check for builds...
3:46:37 PM | Check for builds...
node-build-monitor is listening on port 3000
3:46:51 PM | 178 builds found....
3:46:51 PM | builds changed
3:46:54 PM | Check for builds...
3:46:54 PM | Check for builds...
undefined:1
..
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/home/mwojcie/remote-git/node-build-monitor/node_modules/jenkins-api/lib/main.js:177:33)
    at Request.self.callback (/home/mwojcie/remote-git/node-build-monitor/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/mwojcie/remote-git/node-build-monitor/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/mwojcie/remote-git/node-build-monitor/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

Perhaps some exception handling is missing.

**Comment by marcells** [comment]
Hm, I don't know your configuration. I made a short try with a free jenkins server I've found and there were no errors.
```
{
 "name": "Jenkins",
 "configuration": {
  "url": "http://dev.jazzteam.org:8080",
  "username": "x2sdemo",
  "password": "x2sdemo",
  "job": "xml2selenium-bestpractices",
  "options": {
    "strictSSL": false
  }
}
```

Maybe the jenkins-api module is not compatible to your Jenkins version or something like that. If you find the issue and it's a problem in the plugin of the build monitor, please feel free to make a pull request.

**Comment by wojciiii** [comment]
I can provide you with more info about my systems if you want. 

I saw no attempt to catch any exceptions thrown by the jenkins-api module. Can this be the issue here?

**Comment by marcells** [comment]
Do you know, why the exception is thrown? Because, due to your log, the builds were found and collected one time. Or did you take a look at https://github.com/jansepar/node-jenkins-api, if there are some open issues?

**Comment by wojciiii** [comment]
A reverse proxy is part of our infrastructure - this is sometimes not working correctly and it seems that it returns ~half of the data jenkins is supposed to return in a call to the API. I would expect either the API or the user of the API to retry the request or do some kind of error handling if the request fails.

**Comment by marcells** [comment]
Ah, I see, this should be a job for your sysadmin. I think you've problems with other services, too. ;-)

You're right, that's a general problem, which should be handled by the monitor itself. I think the best solution is to catch the error, and log it to the console, don't update the builds and wait for the next interval. Should this fix your problem?

**Comment by wojciiii** [comment]
I think so. I really like this monitor and would love to use it for looking at results of specific Jenkins jobs. :)

**Comment by marcells** [comment]
Alright, I currently have some other important stuff to do. If you want, you can fix it by yourself and make a pull request or wait a bit until I find some time (maybe tomorrow or on sunday).

**Comment by wojciiii** [comment]
No rush. I think that fixing this will make your monitor more robust so that would be in your interest. ;-)

**Comment by marcells** [comment]
So, I improved the error handling now. But the parse errors can not be solved (in a nice way), because they occur in the callback of the jenkins-api module. I made a pull request, so that the errors are returned in the callback properly. When it's merged and the npm package is updated, the build monitor shouldn't crash again.

https://github.com/jansepar/node-jenkins-api/pull/49

**Comment by marcells** [comment]
I removed the jenkins-api module now, because the maintainer doesn't react on my pull request. The error with the bad response should now be handled properly.

**Comment by kub1x** [comment]
Hey, @marcells, just to let you know, I started helping with the [node-jenkins-api](https://github.com/jansepar/node-jenkins-api) and managed to add the PRs and much more. If you're willing to give it a try, the project should be pretty much "alive" now.

**Comment by marcells** [comment]
Thanks for the info. But for now everything ist working fine and the api calls aren't top complicated. So, I won't change it. 😉
