### ISSUE TITLE
An error occured when fetching builds... "true" - error definition ?

### ISSUE THREAD

**Issue by peterduchnovsky** [marcells/node-build-monitor#225]
I am unable to set jenkins job/view monitoring due to this error, any idea what's going on ?

![cttodqU1hb](https://user-images.githubusercontent.com/54581833/87683876-dc5ccf80-c781-11ea-8270-eb76367cb464.jpg)

**Comment by peterduchnovsky** [comment]
My colleague found out where the problem was.. you were defining joburl manually instead of using the url provided from api call.

This change helped:
![image](https://user-images.githubusercontent.com/54581833/87910235-fd673e00-ca69-11ea-889b-6576ee9e43e0.png)

**Comment by marcells** [comment]
You could make a PR, if you want to, so that everyone can benefit of your bugfix.

**Comment by pduchnovsky** [comment]
#227
