### ISSUE TITLE
Cannot see job details when working with Jenkins

### ISSUE THREAD

**Issue by benbracha** [marcells/node-build-monitor#3]
Hi,

This looks very cool project and I'm trying to integrate it with my team's Jenkins.
I configured config.json with two jobs we have, and I do get the jobs, but only with their build number and status. On the documents, I could see that much more data can be visible (job's name, running status and more).

Probably I'm configuring something wrong?

Here is what I get (as you can understand from the build numbers, there are 2 interleaving jobs here):

![image](https://cloud.githubusercontent.com/assets/3404050/5686499/07651ae0-984c-11e4-8079-2db62892828a.png)

**Comment by marcells** [comment]
Hi,

you did everything right.

The build monitor has a responsive screen design. The problem is that the resolution of your screen is a bit to low to show all details.

I'm currently thinking about a theming mechanism, which would solve your problem. Another solution is to modify the current design, to be able to show more details for low-resolution devices.

Could you tell me the resolution of your screen?

**Comment by benbracha** [comment]
Oh.. actually I had a feeling it is related to that :) I tested your project on my macbook pro 13" 1280X800. Probably this is the issue...

BTW - I couldn't run things with Docker. This is my first trial with Docker, so I probably missing something.
But after installing docker and trying to run docker as detailed, I got this one:

׳׳׳
<benbracha@bens-mbp:docker> $ docker build -t my-node-build-monitor

Usage: docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH

  --force-rm=false     Always remove intermediate containers, even after unsuccessful builds
  --no-cache=false     Do not use cache when building the image
  --pull=false         Always attempt to pull a newer version of the image
  -q, --quiet=false    Suppress the verbose output generated by the containers
  --rm=true            Remove intermediate containers after a successful build
  -t, --tag=""         Repository name (and optionally a tag) to be applied to the resulting image in case of success
׳׳׳

**Comment by marcells** [comment]
In the documentation there is a period at the end of the command. It's important cause it tells Docker to take the Dockerfile from the current path.

`docker build -t my-node-build-monitor .`

**Comment by benbracha** [comment]
Oops :)

Ok, now I get this one:
```
<benbracha@bens-mbp:docker> $ docker build -t my-node-build-monitor .
Sending build context to Docker daemon
FATA[0000] Post http:///var/run/docker.sock/v1.16/build?rm=1&t=my-node-build-monitor: dial unix /var/run/docker.sock: no such file or directory
```

Maybe I didn't install Docker right?

**Comment by marcells** [comment]
Yes, it looks like a installation/execution problem of Docker itself. I run Docker on Linux. So, I don't have any experiences on the Mac. You have to check the docs of Docker or boot2docker.

We seem to drift away from the original issue. If you have further problem, feel free to open a new issue for it.

**Comment by benbracha** [comment]
Indeed. Thanks a lot!

**Comment by marcells** [comment]
Hey, I've added support for themes now. If you want to, you could create a theme which works great for smaller devices and send a pull request. You just need to create one html template and one stylesheet.

[Show default theme](http://builds.mspi.es), [Show list theme](http://builds.mspi.es/?theme=list)
[More information how to create a theme](https://github.com/marcells/node-build-monitor#theming-support)

Would that be okay for you?

**Comment by benbracha** [comment]
That's pretty cool thanks! I'll take a look. I plan to display this on big screen so the default theme will be good. But this flexibility can help.
