### ISSUE TITLE
 TFS Project Collection named DefaultCollection was not found.

### ISSUE THREAD

**Issue by navrenga** [marcells/node-build-monitor#32]
Trying to install using docker

"name": "Tfs",
"configuration": {
"collection": "DefaultCollection",
"accountname": "xxxx@mail.com",
"username": "xxxx@mail.com",
"password": "xxxxx"
}

VSTS url https://xxxx.visualstudio.com

Error: The TFS Project Collection named DefaultCollection was not found.
at /build-mon/app/services/Tfs.js:75:28
at Request._callback (/build-mon/app/services/Tfs.js:23:21)
at Request.self.callback (/build-mon/node_modules/request/request.js:199:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request. (/build-mon/node_modules/request/request.js:1036:10)
at emitOne (events.js:101:20)
at Request.emit (events.js:188:7)
at IncomingMessage. (/build-mon/node_modules/request/request.js:963:12)
at emitNone (events.js:91:20)
@rengago

**Comment by marcells** [comment]
Sorry for the late response. I see the issue. The configuration seems to be wrong.

1. The `accountname` is only the *xxxx* part of the url.
2. The `username` and `password` have to be created in the VS Online (login to https://xxxx.visualstudio.com -> hover over your avatar (top right) -> Security -> Alternate authentication credentials -> create the credentials)

```
{
  "name": "Tfs",
  "configuration": {
    "collection": "DefaultCollection",
    "accountname": "[xxxx from https://xxxx.visualstudio.com]",
    "username": "[Username (second) from the alternate authentication credentials settings]",
    "password": "[Password from the alternate authentication credentials settings]"
  }
}
```

Please let me know, if everything works for you.

**Comment by marcells** [comment]
I've updated the section in the Readme.md to make the necessary configuration steps more clear.

**Comment by navrenga** [comment]
marcells,
Thanks for your response.
My config.json
{
  "monitor": {
    "interval": 300000,
    "numberOfBuilds": 12,
    "debug": false
  },
  "services": [
    {
      "name": "Tfs",
      "configuration": {
        "collection": "DefaultCollection",
        "accountname": "xxxxxx",
        "username": "xxxxxx",
        "password": "xxxxxx"
      }
    }
   ]
}

I am not getting any errors in docker logs  now. 

Docker logs 
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
node-build-monitor is listening on port 3000

but when i try to access  http://localhost:12345/
I see only Blank Black screen without any data.

**Comment by marcells** [comment]
Silliy question. You have finished or running builds in your DefaultCollection? ;-) Cause I tried it and it worked for me. You could try to use a smaller interval. Maybe `10000` and set the debug flag to `true`.

**Comment by navrenga** [comment]
yes you are right it is displaying no builds on setting debug. but in vsts 2015 i do have couple of projects and their build definitions  and also builds are running successfully in those projects.

**Comment by marcells** [comment]
Hm, maybe you can try to set more console.log() calls in the service to
find the issue. With my account everything works fine.

Rengarajan <notifications@github.com> schrieb am Do., 1. Dez. 2016, 03:03:

**Comment by marcells** [comment]
Did you find out what's going on here?

**Comment by navrenga** [comment]
sorry for the late reply. Still No luck. I doubt this may be due to non XAML build defintion.

Similar example may be 
https://teambuildscreen.codeplex.com/workitem/64629
https://teambuildscreen.codeplex.com/workitem/65108

**Comment by marcells** [comment]
Oh, you're right. That could be. I think, I only tried it  with an old TFS 2013 on-premise and Xaml builds. Could you switch your builds to non-xaml? They are or will be deprecated in future.

**Comment by navrenga** [comment]
After switching to non-xaml , Issue still persist.:(

**Comment by marcells** [comment]
Hm, very strange. I think, I've exactly the same configuration as you.

You could try to query the build via OData (https://tfsodata.visualstudio.com/). If you get some results, when querying the builds, then it should work with the build monitor, too.

**Comment by marcells** [comment]
Is your issue solved in the meantime?

**Comment by rengago** [comment]
No marcells. still helpless. I will try much more and reopen this case if this was actual issue to me.
Thanks for your help.

**Comment by marcells** [comment]
Okay, thanks for the info. I'll close it for now.
