### ISSUE TITLE
Filter branches

### ISSUE THREAD

**Issue by morph027** [marcells/node-build-monitor#35]
First of all, thanks for your work!

Can we add the ability to filter branches somehow (we are using on premise Gitlab)? We want to monitor same branch on different slugs. Devs should keep an eye on their own branches locally ;)

**Comment by marcells** [comment]
Thank you. :-)

Hm, your request is similar to #26. I don't want to be dependent on the underlying VCS, cause the build-monitor is very common and should work for all build systems/configurations in the same way.

Maybe a general property `details.repository` with an object (which isn't displayed, but can be filtered) could be possible. I'll then extend the filter in the frontend to respect the values (not the keys) of this property, too.

Is it possible for you to implement the property and make a pull request? Here's the correct place: https://github.com/marcells/node-build-monitor/blob/master/app/services/GitLab.js#L164
It should look like this:
```
return {
            ...
            url: getBuildUrl(project, build),
            details: {
                  repository: getRepositoryDetails(...) // should return { branch: 'master' } or { }, if no details exist
             }
        };
```

I'll extend the frontend, when you've finished. Okay?

**Comment by morph027** [comment]
Thanks,sure, I'm gonna try this and let you know.
