### ISSUE TITLE
Jenkins jobs do not show Running status

### ISSUE THREAD

**Issue by dickschoeller** [marcells/node-build-monitor#36]
The Jenkins API returns a status of SUCCESS when builds are running. It is necessary to check the value of building to identify a running job. This impacts the calls to and implementation of getStatus and getStatusText in Jenkins.js.

**Comment by marcells** [comment]
Hey, thank you for reporting the issue. Could you make a pull request with the fix? Otherwise it will take at least a week for me to take a look at the issue.
