### ISSUE TITLE
Can you please add support NTML authentication support.

### ISSUE THREAD

**Issue by omerfarukz** [marcells/node-build-monitor#38]

**Comment by marcells** [comment]
Could you please provide a bit more information?

**Comment by omerfarukz** [comment]
Yes, we are using a team foundation system and can not use OAuth or basic authentication. We have only Ntlm. In this case we used node http/ntlm libraries and modified this library. So, we can easily integrated in our system a month ago. Thanks you.

**Comment by marcells** [comment]
Is your change compatible and can you offer it as a pull request? So other people could benefit from it. Otherwise I would close this issue.

**Comment by freepee** [comment]
A NTLM-solution would be perfect for me to. My organization only supports Windows authentication.
