### ISSUE TITLE
Problem to connect to on-premise TFS

### ISSUE THREAD

**Issue by freepee** [marcells/node-build-monitor#39]
I have some problem connecting the build-monitor to our own TFS. In the config.json we have this:
`"services": [
 {
      "name": "TFS",
      "configuration": {
        "url": "http://q45tfs:8080/tfs/DefaultCollection",
        "username": "*****************",
        "password": "*********"
      }
    }
  ]`

Running with this configuration gives the following error message:

`{ Error: connect ETIMEDOUT 168.61.37.249:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '168.61.37.249',
  port: 443 }`

We do not use SSL and TFS is not available over the Internet.
Where to the address 168.61.37.249 come from? Any help or advice is appreciated.

**Comment by marcells** [comment]
Just as an information. I made an IP address lookup. The IP range 168.61.0.0-168.63.255.255 is claimed by Microsoft.

So, now to your problem. You've accidentally used the plugin vor the Visual Studio Online service, instead of the on-premise service. If you're using TFS 2015 please use the plugin [Team Foundation Server (on-premise)](https://github.com/marcells/node-build-monitor#team-foundation-server-2015-on-premise) (Tfs2015). If you're using TFS 2017, then use the same plugin as for TFS 2015, but [claim a personal access token](https://www.visualstudio.com/en-us/docs/setup-admin/team-services/use-personal-access-tokens-to-authenticate) and use this as the credentials.

Please let me know, if this answer fixed your issue.

**Comment by freepee** [comment]
Thank you for take time to answer my request.


I not have the correct tfs2015-configuration with username and password (for now, not access token). But I get this error:


node-build-monitor is listening on port 3000
C:\code\node-build-monitor\app\services\Tfs2015.js:30
            for (var i = 0; i < body.value.length; i++) {
                                          ^

TypeError: Cannot read property 'length' of undefined
    at forEachResult (C:\code\node-build-monitor\app\services\Tfs2015.js:30:43)
    at C:\code\node-build-monitor\app\services\Tfs2015.js:85:17
    at Request._callback (C:\code\node-build-monitor\app\services\Tfs2015.js:23:21)
    at Request.self.callback (C:\code\node-build-monitor\node_modules\request\request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\code\node-build-monitor\node_modules\request\request.js:1036:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\code\node-build-monitor\node_modules\request\request.js:963:12)


It seems that your code expects something in the response body that it doesn't get......


Is there any requirements regarding what needs to be set on the TFS-server? Any ports that needs to be opened etc?


We are running the TFS server without Intenet access, it only accessible in-house.


Fred Petter.
________________________________
Fra: Marcell Spies <notifications@github.com>
Sendt: 14. mars 2017 21:04
Til: marcells/node-build-monitor
Kopi: freepee; Author
Emne: Re: [marcells/node-build-monitor] Problem to connect to on-premise TFS (#39)


Just as an information. I made an IP address lookup. The IP range 168.61.0.0-168.63.255.255 is claimed by Microsoft.

So, now to your problem. You've accidentally used the plugin vor the Visual Studio Online service, instead of the on-premise service. If you're using TFS 2015 please use the plugin Team Foundation Server (on-premise)<https://github.com/marcells/node-build-monitor#team-foundation-server-2015-on-premise> (Tfs2015). If you're using TFS 2017, then use the same plugin as for TFS 2015, but claim a personal access token<https://www.visualstudio.com/en-us/docs/setup-admin/team-services/use-personal-access-tokens-to-authenticate> and use this as the credentials.

Please let me know, if this answer fixed your issue.

**Comment by freepee** [comment]
Hi again


PS C:\code\node-build-monitor> node .\app\app.js
10:24:38 | Check for builds...
node-build-monitor is listening on port 3000
C:\code\node-build-monitor\app\services\Tfs2015.js:30
            for (var i = 0; i < body.value.length; i++) {
                                          ^

TypeError: Cannot read property 'length' of undefined
    at forEachResult (C:\code\node-build-monitor\app\services\Tfs2015.js:30:43)
    at C:\code\node-build-monitor\app\services\Tfs2015.js:85:17
    at Request._callback (C:\code\node-build-monitor\app\services\Tfs2015.js:23:21)
    at Request.self.callback (C:\code\node-build-monitor\node_modules\request\request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\code\node-build-monitor\node_modules\request\request.js:1036:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\code\node-build-monitor\node_modules\request\request.js:963:12)



I still get the same exception and I think I have the correct information, there must be something missing....


I have this config.json:


{
  "monitor": {
    "interval": 5000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "debug": true
  },
  "services": [
  {"name": "Tfs2015",
    "configuration": {
      "url": "http://q45tfs:8080/tfs/DefaultCollection/ISY.ByggOffice/",
      "username": "norconsultad\\*********",
      "password": "************"
    }
  }
  ]
}


If I navigate to the url in a browser I get the TFS Dashboard:

[cid:e969a4ad-ec41-45e4-9f41-8555f84dd49c]



________________________________
Fra: Marcell Spies <notifications@github.com>
Sendt: 15. mars 2017 21:15
Til: marcells/node-build-monitor
Kopi: freepee; Author
Emne: Re: [marcells/node-build-monitor] Problem to connect to on-premise TFS (#39)


You have to append the team project in the URL. See the settings<https://github.com/marcells/node-build-monitor/blob/master/README.md#team-foundation-server-20152017-on-premise>.

No, you don't need to open any special ports, but the port, which is used to access the web frontend (8080 by default).

**Comment by freepee** [comment]
We have TFS 2015 so token is not the issue right now.



________________________________
Fra: Marcell Spies <notifications@github.com>
Sendt: 15. mars 2017 21:17
Til: marcells/node-build-monitor
Kopi: freepee; Author
Emne: Re: [marcells/node-build-monitor] Problem to connect to on-premise TFS (#39)


If you use TFS 2017, you have to generate an access token. That is described in the Readme, too.

Let me know if my info helped you.

**Comment by freepee** [comment]
Hi
I have fiddled around with Fiddler and when sending a request I get the response of an html-page with information that I don't have access.

` <body>
        <div id="header">
            <h1>Server Error</h1>
        </div>
        <div id="content">
            <div class="content-container">
                <fieldset>
                    <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
                    <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
                </fieldset>
            </div>
        </div>
    </body>
</html>`

I'll figure that out and it will probably work fine :-)

**Comment by marcells** [comment]
Hm, try removing the trailing `/` from the url setting. The rest of the configuration looks good as long as you do use Team Foundation Server 2015.
If that doesn't work you have to check with fiddler/postman, why you're not authenticated correctly.

**Comment by mikestichling** [comment]
@freepee Did you solve your problem?

I found this same issue when authenticating against our on-premise TFS server. Eventually I tracked it down to having Basic Authentication turned off.

**Comment by marcells** [comment]
I'll close this issue for now. We use(d) it with TFS 2015 and 2017 and it is working well. Fell free to reopen the issue, if it is still a problem for you.

**Comment by nicksterx** [comment]
I don't think it works with NTLM authentication. I get the same error that @freepee was getting about the 401 unauthorized. 
my config.json
```{
  "monitor": {
    "interval": 30000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "debug": true
  },
  "services": [
    {
      "name": "Tfs2015",
      "configuration": {
        "url": "https://foo.bar/tfs/Collection/Project",
        "authentication": "ntlm",
        "username": "DOMAIN\\user",
        "password": "hunter2"
      }
    }
  ]
}
