### ISSUE TITLE
Cut new release?

### ISSUE THREAD

**Issue by Brantone** [marcells/node-build-monitor#40]
Hey,
Originally I was curious about cutting a new release for all the changes (if they're all completed), but then I also noticed that "latest" is still showing as 0.9.5 (https://github.com/marcells/node-build-monitor/releases) , whereas code is already up to 0.9.8 (and I assume latest changes will bump that up).
Thanks in advance.

**Comment by marcells** [comment]
I only updated the version number, when something in the frontend changes. Cause then the web frontend reloads automatically, after the service is updated and restarted.

**Comment by Brantone** [comment]
Initially, I was thinking less of an "automated version increment" and more just generic release of features (front or back end) and bumping https://github.com/marcells/node-build-monitor/blob/master/package.json#L3 based on something like semver.org

**Comment by marcells** [comment]
Now I easily can bump a version with `grunt bump`. This will also create a new [tag/release](https://github.com/marcells/node-build-monitor/releases) automatically. In addition for each tag a [separate docker image](https://store.docker.com/community/images/marcells/node-build-monitor/tags) is built. So, if there are any issues with a new version, you can revert it easily.

**Comment by Brantone** [comment]
Awesomeness! 👍
