### ISSUE TITLE
latestBuildOnly not working for all services

### ISSUE THREAD

**Issue by arunkumarsundaramurthy** [marcells/node-build-monitor#55]
Looks like if the latestBuildOnly flag is set.. only the first build is considered.. this will work fine for services like Travis where we have only one slug.. but for services like gitlab where we have option to specify multiple slugs.. this feature is broken..

**Comment by marcells** [comment]
Hm, you're right. Is it an option for you to create a configuration for each slug instead of using the wildcard?

**Comment by AlexKel** [comment]
Yeah, this is definitely not working.. A workaround is to create a service object for each slug.

**Comment by marcells** [comment]
I'll close this issue right now. The workaround should be enough for most of the people who need this case.
