### ISSUE TITLE
Gitlab build displaying all JOBS, while the intent for a monitor is the state of a specific Branch

### ISSUE THREAD

**Issue by karthik-krishnan** [marcells/node-build-monitor#57]
Typically,  If I have a Branch(say Master Branch), am interested to know the state of the branch at a given point(after every commit).  However, for Gitlab, it shows all the jobs that are scheduled, so if I have a branch, which has 2 commits(one causing an issue and the other subsequently fixing it). It would end up as two Jobs and the build monitor displays both of them.  Say one is Green and the other is Red, what do I Infer from it w.r.to the "current state" of my Branch?

**Comment by marcells** [comment]
Hm, the build monitor should show each build of the configured project(s). Maybe this configuration could be a solution for you: https://github.com/marcells/node-build-monitor/pull/33

If I misunderstood your issue, please let me know it.

Kind regards
Marcell

**Comment by marcells** [comment]
Can this issue be closed?

**Comment by karthik-krishnan** [comment]
Yes. Thanks. 

Best regards,
Karthik.
