### ISSUE TITLE
Gitlab to use pipeline api instead of job api

### ISSUE THREAD

**Issue by karthik-krishnan** [marcells/node-build-monitor#58]
Since Build Dashboard monitor is really interested in reflecting the current state of a specific branch and not really the "latest build(job)" in a specific branch, it would be useful to use the pipeline API to reflect the same.  The API is 
/api/v4/projects/<project_id>/pipelines?ref=master

I will make the necessary changes and raise a pull request as well soon.

**Comment by marcells** [comment]
Does the pull request #59 solve your issue, when it is integrated? Please be aware of it, so that you don't run into any conflicts.

**Comment by karthik-krishnan** [comment]
Yes. Arun raised the PR. 

Best regards,
Karthik.

**Comment by marcells** [comment]
Fixed in pr #59.

**Comment by karthik-krishnan** [comment]
Hi Marcell,

I had raised PR #60 and 61.  It would be great if you could review the same.

Best regards,
Karthik Krishnan.
http://karthiks.in
