### ISSUE TITLE
improving Gitlab-CI display

### ISSUE THREAD

**Issue by prune998** [marcells/node-build-monitor#64]
I have two features I would like to have in the gitlab-ci plugin.

1) Gitlab-CI have different stages during a build, like "test", "build", "deploy". The interface is not showing this information.

2) beeing able to display only a number of builds per project. 
For now I'm displaying all the builds for "stared" projects. Let's say I display 10 builds and I try to build "project A" 11 times, I will only see the status of project A in the dashboard. 
I would like to be able to say "I want the last 3 builds of each project", maybe grouped by project... 

I'm really no nodejs expert so it will be hard for me to help with that, but looking at your code I'm really sure it could be quite easy for a trained dev : 

maybe for 1) it would be a rewrite of the project name to include the "stage" ?
for 2) it would be a more complicated filter, at the same place where you sort by date/project ?

I'll ask a friend of mine who is a nodejs dev if he can help, but let me know if you have any clue/time for such features.

Great work btw !

**Comment by AlexKel** [comment]
I'm too interested in the first feature requested here (pipeline stages display). If one of the stages failed it's really handy to see which one straight away. I might be able to contribute if I'll find some free time.

**Comment by ntamas** [comment]
> beeing able to display only a number of builds per project.
We also needed this so we have implemented this in our fork: https://github.com/milinnovations/node-build-monitor/commit/3d13b3f09ed088b26652a2b90f7660b780808e6d

**Comment by marcells** [comment]
Closed with pr #75.

**Comment by ntamas** [comment]
Note that my pull request did not handle point 1 from the original issue, i.e. this one:

> Gitlab-CI have different stages during a build, like "test", "build", "deploy". The interface is not showing this information.

Maybe it would be good either to leave this issue as open or create a new issue separately.

**Comment by prune998** [comment]
Will create another issue for point 1.
Thanks.

**Comment by prune998** [comment]
added as https://github.com/marcells/node-build-monitor/issues/76
