### ISSUE TITLE
Can't add gitlab

### ISSUE THREAD

**Issue by fireclay** [marcells/node-build-monitor#66]
I apologize if this is the wrong place to ask this!

I am trying to use this tool with Team City and Gitlab. 
It works great for Team City but it does not show any results from Gitlab. 
Can someone please give some idea what I am doing wrong?
I don't quite understand the "slugs" field so that's probably the problem?

We're using GitLab Community Edition 8.6.3 and the link to the project I want to see builds from is https://gitlab-group.st.myDomain.net/mbs/mbsInternal

This is my .json file:

```
{
  "monitor": {
    "interval": 30000,
    "numberOfBuilds": 1,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "debug": true
  },
  "services": [
    {
      "name": "TeamCity",
      "configuration": {
        "url": "http://myUser:myPwd@teamcity.myDomain.net:8080",
        "buildConfigurationId": "Mbs_MasterOnLinux64bitAbs1",
        "branch": "master"
      }
    },
    {
    "name": "GitLab",
    "configuration": {
      "url": "https://gitlab-group.st.myDomain.net:443",
      "token": "myToken",
      "additional_query": "&search=mbs&starred=true",
      "slugs": [
      {
        "project": "mbs/mbsInternal",
        "ref": "master"
      }
      ]
    }
  }
  ]
}
```

**Comment by marcells** [comment]
I'm not using the GitLab service. Maybe @arunkumarsundaramurth or @datakurre are able to help you here.

**Comment by datakurre** [comment]
Just url and token should be enough for displaying all projects for which the token has read access to.

**Comment by fireclay** [comment]
@datakurre Thank you, I tried that but it did not help. 
Will the tool create an error log somewhere?

**Comment by sanjusoftware** [comment]
@fireclay the configuration looks fine ... I have tried similar conf on my gitlab privately hosted account and it works fine .. is there any specific error that you are getting? The only reason I can think of why you are not able to see any builds (if thats the case) is that the `additional_search` might not be resulting into any builds at all....

can you try first just removing the `additonal_query` from your configuration and try again .. or better try curl query with the params that you are trying directly on command line to see if it results into anything .. you can grab the query by putting a consolr.log just before [this](https://github.com/marcells/node-build-monitor/blob/master/app/services/GitLab.js#L31) statement in `GitLab.js` file

**Comment by fireclay** [comment]
@sanjusoftware Thank you for your reply!
I don't get any specific error, I just can't see any builds from gitlab. I tried removing everything except token and URL and it did not help so I don't think the `additional_search` is the problem.  Perhaps our IT department has blocked using the Gitlab REST API. I will ask them!

I am not familiar with curl at all. Could you write a more detailed description?

**Comment by sanjusoftware** [comment]
@fireclay that could be a reason, however, I think you can grab the errors by looking at the server logs ... what do you see there?

**Comment by fireclay** [comment]
@sanjusoftware Can you describe how to check the server logs please?

**Comment by sanjusoftware** [comment]
@fireclay it actually depends how you are running your service... if u r running it in a container, the you'll have to get in the contaner and then look at the logs at the console... it you are running it directly on command line, then the logs are printed on the standard output ... its better to ask your admin who is running the service

**Comment by fireclay** [comment]
Hi, thanks all for your suggestions.
I give up now, I guess something is blocked in our gitlab instance.
