### ISSUE TITLE
TeamCity 9

### ISSUE THREAD

**Issue by TKegelaers** [marcells/node-build-monitor#7]
When retrieving builds for TeamCity 9 I get the following error:

 Cannot read property 'build' of undefined.

Something is going wrong at `selectMany(data, function (x) { return x.build || []; });`
in TeamCity.js line 46

**Comment by marcells** [comment]
Does that happen all the time or just occasionally?

**Comment by TKegelaers** [comment]
It happens all the time.
When I type in the url to get the builds via the browser i receive result.
`http://pallas/httpAuth/app/rest/buildTypes/id:bt91/builds`

**Comment by TKegelaers** [comment]
I've found the problem. There was something wrong with the configuration.
Issue can be closed.
