### ISSUE TITLE
Bitbucket Pipelines support

### ISSUE THREAD

**Issue by ddetoni** [marcells/node-build-monitor#71]
Hi,

Anyone else looking for a [Bitbucket Pipelines](https://bitbucket.org/product/features/pipelines) support? Bitbucket Pipelines is getting better, but right now there is no way to have build monitors. The REST API seems good enough to us build an integration.

Any thoughts on this?

**Comment by marcells** [comment]
Hm, currently not. Feel free to create a new service and make a PR. You can use the TFS 2015 service as a template.

**Comment by ddetoni** [comment]
Thanks, I tried here #81. Please some feedback.
