### ISSUE TITLE
0 buils founds with GitLab

### ISSUE THREAD

**Issue by aborderon** [marcells/node-build-monitor#79]
Hello,
I have a small problems to run node-build-monitor with GitLab.
I use Docker in production, so I have a Dockerfile and a config.js like :

```json
{
  "monitor": {
    "interval": 30000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "debug": true
  },
  "services": [
    {
      "name": "GitLab",
      "configuration": {
        "url": "https://gitlab.mycompagny.fr",
        "token": "myGitlabUserToken",
        "additional_query": "&search=mygroup&starred=true",
        "numberOfPipelinesPerProject": 3,
        "slugs": [
          {
            "project": "mygroup/myproject",
            "ref": "master"
          },
          {
            "project": "mygroup/myproject",
            "ref": "develop"
         }
        ]
      }
    }
  ]
}

```

but I have no results on the website and in my docker logs I get :

$ docker logs --tail all node-build-monitor
> warn:    --minUptime not set. Defaulting to: 1000ms
> warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
> 9:32:37 AM | Check for builds...
> 9:32:37 AM | 0 builds found....
> node-build-monitor 0.9.24 is listening on port 3000
> 9:33:07 AM | Check for builds...
> 9:33:07 AM | 0 builds found....

For information, my Gitlab uses a self-signed certificate.

Thank you for your help ;)

**Comment by marcells** [comment]
@datakurre Do you have any idea what could be wrong with the configuration?

**Comment by marcells** [comment]
@aborderon Could you try to debug the app to see what could be wrong?

**Comment by aborderon** [comment]
Yes @marcells , I found the problem, this is the self-signed certificate that I use with Gitlab.

In the request.js, the `rejectUnauthorized` property to `false` does not work.

I managed to access my GitLab builds by adding the line just below the exports module of GitLab.js but it is not an acceptable resolution :
`module.exports = function () {
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; `

Do you have a better solution?

**Comment by marcells** [comment]
Hm, that's just an environment variable. Please remove your change from `GitLab.js` and try the following.

If you use the executable, just set it in your shell before starting the build-monitor. If you use docker, then take a look [here](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e-env-env-file) how to define an environment variable.

Please let me know, if it worked.

**Comment by aborderon** [comment]
Hello, thank you for your answer. I run node-build-monitor with docker with the following command and it work:

`docker run -d -p 3000:3000 -e NODE_TLS_REJECT_UNAUTHORIZED=0 --name node-build-monitor node-build-monitor`

It would be necessary to add documentation for self signed certificates I think.

I will try to make a pull request to adding docker-compose support. I would take this opportunity to add a configuration with self signed certificates.

Thanks again !

**Comment by marcells** [comment]
Nice to hear! I did update the docs right now. Feel free to make a PR for docker-compose support.

**Comment by fireclay** [comment]
Can I somehow set NODE_TLS_REJECT_UNAUTHORIZED=0 when running the standalone version?

Or can you update the standalone version with this setting?

I tried setting it as a Windows environment variable but I still get 0 builds found...

**Comment by marcells** [comment]
Hm, that should work. At least for the Linux build I tested it.

Did you set it on cmd with `set NODE_TLS_REJECT_UNAUTHORIZED=0` before starting node-build-monitor.exe from the same cmd session?

**Comment by fireclay** [comment]
Hi Marcells, thank for your reply!

Yes I tried that and the variable is printed and set to 0:
```
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = 0
node-build-monitor is starting...
07:39:59 | Check for builds...
node-build-monitor 0.9.27 is listening on port 3000...
```

Now I instead get "check for builds.." and "node-build-monitor is listening on port ... " but there is no message about number of builds? 

With version 9.2 I get 
```
07:39:44 | Check for builds...
07:39:44 | 0 builds found....
node-build-monitor 0.9.20 is listening on port 3000
```

**Comment by marcells** [comment]
So there was a response with 0 builds now. Could it be, that your configuration is wrong?

**Comment by kasperschnack** [comment]
Hi I'm having this same problem. The server is running but I can't see in any logs why no builds are fetched. Only output I git from docker-compose logs is this:

`docker-compose logs
Attaching to docker_node-build-monitor_1
node-build-monitor_1  | warn:    --minUptime not set. Defaulting to: 1000ms
node-build-monitor_1  | warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
node-build-monitor_1  | error: Could not read .foreverignore file.
node-build-monitor_1  | error: ENOENT: no such file or directory, open '/build-mon/app/.foreverignore'
node-build-monitor_1  | Printing environment Variables...
node-build-monitor_1  |     PORT = unset (Default: 3000)
node-build-monitor_1  |     NODE_TLS_REJECT_UNAUTHORIZED = unset (Default: 1)
node-build-monitor_1  | node-build-monitor is starting...
node-build-monitor_1  | node-build-monitor 0.9.55 is listening on port 3000...`

I'm guessing NODE_TLS_REJECT_UNAUTHORIZED maybe should be set to 0? How can I do this when running via docker-compose? Thank you!
