### ISSUE TITLE
can i somehow show private builds?

### ISSUE THREAD

**Issue by kakulukia** [marcells/node-build-monitor#8]
currently the build monitor stays empty

**Comment by marcells** [comment]
Could you please provide more information? Which service do you use? Are there any errors or is there any output in the console?

**Comment by kakulukia** [comment]
I should somehow be able to put my access token in the config file to be able to see my private repos in the monitoring dashboard.
I'm using Travis with private repos in Github.

**Comment by marcells** [comment]
I currently don't own a private Travis account. So, I tried to implement the access to private builds by only using the documentation.

Please check and test my changes in the travis-pro branch in commit bd96009d5b6b709609a41aba87cc7fa06ec4528a. Define `travis-ci.com` as `url` and your access token as `token` in the configuration. If it's working, I'll merge it into master.

If there are still some issues, which you were able to fix, it would be great if you could send me a pull request.

**Comment by kakulukia** [comment]
thx for the quick fix .. but sadly i cant confirm it yet .. i have to figure out first (together with the travis support team) why their API does not report any builds although i see everything on the webpage .. so the build monitor gets no data to display .. wich is weird!

i will report back as soon as this is sorted out

**Comment by kakulukia** [comment]
but i bet this should work once the API actually reports my data

**Comment by kakulukia** [comment]
it works!

BUT i kinda have two complains, about the current version

1. could you leave the config.json out of versioning but instead checkin a config.json.example to have a clean repo even when setting up my own config ..

2. i have multiple (7) repositories and just listing the builds will kinda hide that other not so active repos have some problems because the more recent "news" push the bad new towards the bottom of the page. Id like to be able to switch between builds and repos or even have some cool combinations of both .. im gonna think of a solution over the weekend to come up with a good solution to combine the two worlds .. and might be able to even help coding it .. whats your take on that?

**Comment by marcells** [comment]
Great, then I will soon merge the changes into master.

1. If you run the build monitor in a Docker container, then you can copy the content of the `docker` sub folder in the repo to a place on your disk and just run the script `run_without_tfsproxy.sh` (the Docker image will be built automatically from the master branch).

2. Hm, I understand your problem. Did you try to increase the `numberOfBuilds` configuration property? Otherwise we could implement some kind of filter (by build project/definition), when the mouse is moved.

(Sorry for the late response. I was on vacation.)

**Comment by kakulukia** [comment]
sorry for the even later response .. we are going to organize the monitoring differently .. i think i wont have time for the new design .. jst wanted to let you know.
