### ISSUE TITLE
body.value undefined

### ISSUE THREAD

**Issue by Grifplex** [marcells/node-build-monitor#85]
I'm getting the following error for our on-site TFS2015 build server. I get this with the latest release for windows, linux, and directly running from node on a Raspberry Pi.

```
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = 0
node-build-monitor is starting...
11:13:53 AM | Check for builds...
node-build-monitor 0.9.27 is listening on port 3000...
C:\snapshot\node-build-monitor\app\services\Tfs2015.js:27
            for (var i = 0; i < body.value.length; i++) {
                                          ^

TypeError: Cannot read property 'length' of undefined
    at forEachResult (C:\snapshot\node-build-monitor\app\services\Tfs2015.js:27:43)
    at C:\snapshot\node-build-monitor\app\services\Tfs2015.js:82:17
    at Request._callback (C:\snapshot\node-build-monitor\app\requests.js:23:11)
    at Request.init.self.callback (C:\snapshot\node-build-monitor\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\snapshot\node-build-monitor\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\snapshot\node-build-monitor\node_modules\request\request.js:1091:12)
```
Have I not configured it correctly?
It exits with this error with the several valid log-ins I have tried and for all my projects that I am able to view from a browser at the given url.
```
{
  "monitor": {
    "interval": 15000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "debug": true
  },
  "services": [
    {
      "name": "Tfs2015",
      "configuration": {
        "url": "http://<MyBuildServer>:8080/tfs/DefaultCollection/<MyProject>",
        "username": "<MyUserName>",
        "password": "<MyPassword>"
      }
    }
  ]
}
```

**Comment by marcells** [comment]
Hi,

your configuration looks correct to me. Could you write a `console.log(body)` in line 27 and post the output? Maybe the same in line 80 would be helpful, too.

Kind regards

**Comment by Grifplex** [comment]
From `console.log(body)` I get the following in the body of an HTML page:
> 401 - Unauthorized: Access is denied due to invalid credentials.

I have also outputted the URL being requested into chromium on the pi and I get a log-in prompt followed by a proper JSON string of the builds using the same credentials in the config, so I don't know why it wouldn't work in the node-build-monitor.

**Comment by marcells** [comment]
Please try to use the new Tfs service. There are similar closed issues.

**Comment by gas421** [comment]
Hello, I'm having exaclty the same issue: TFS2015 on premises, even the credentials are fine body.value is undefined.

The only solution is to migrate to new TFS ?

**Comment by marcells** [comment]
No, you don't have to upgrade your TFS server (but it would be a good thing, cause it contains lots of new features).

You could try to use file:///android_asset/md/#visual-studio-team-services-and-team-foundation-server.

**Comment by gas421** [comment]
I tried to use the node-build-monitor with a TFS 2015 on premises, with and without NTLM adding some console.log to debug:
- the TFS URL printed is correct
- the credentials are correct (double checked)
- authentication with and without "ntlm"
- NODE_TLS_REJECT_UNAUTHORIZED set 1 and 0
- config is correct:

{
  "monitor": {
    "interval": 30000,
    "numberOfBuilds": 12,
    "latestBuildOnly": false,
    "sortOrder": "date",
    "expandEnvironmentVariables": false,
    "debug": true
  },
  "services": [
    {
      "name": "Tfs2015",
      "configuration": {
        "url": "http://<<TFS server>>:8080/tfs/<<collection>>/<<project>>",
        "username": "<<username>>",
        "password": "<<password>>",
        "slug": "node-build-monitor",
        "authentication": "ntlm"
      }
    }
  ]
}

**Result is always the same**: 401 - Unauthorized: Access is denied due to invalid credentials.

Something to suggest to solve the issue?

**Comment by marcells** [comment]
You configuration looks correct (slug isn't needed, but shouldn't lead to an error).
`NODE_TLS_REJECT_UNAUTHORIZED` is only needed if you use HTTPS with a self-signed certificate.

Could it be that you forgot the domain in the username? Did you escape the backslash between domain and username correctly (two backslashes)?

```{
  "name": "Tfs2015",
  "configuration": {
    "url": "http://tfs-server:8080/tfs/DefaultCollection/TeamProject",
    "username": "domain\\buildadmin",
    "password": "buildadmin_password"
  }
}```

You could check your network traffic with fiddler and take a look at the headers/url called by the build-monitor to investigate the issue.

**Comment by marcells** [comment]
You can also use the [Tfs service](https://github.com/marcells/node-build-monitor#visual-studio-team-services-and-team-foundation-server) (not Tfs2015). It uses the REST Api version 2, which should be compatible with TFS 2015 (see [compatibility matrix](https://docs.microsoft.com/en-us/vsts/integrate/concepts/rest-api-versioning?view=vsts)).

I made it compatible right now to use it with TFS on-premise services which don't use SSL. So please pull the changes or download the new release of today (Version 0.9.44).

The configuration is a bit different but you can achieve the same. `pat` is your account password. In the `queryparams` you can define the build definitions,etc. Take a look at the TFS Build API docs for more query/filter options.

```
{
  "name": "Tfs",
  "configuration": {
    "url": "https://{youraccount}.visualstudio.com or http://tfs-server:8080/tfs",
    "collection": "DefaultCollection",
    "project": "projectname",
    "username": "domain\\username",
    "pat": "personalaccesstoken",
    "queryparams": "&branchName=refs/heads/master&definitions=4,5,6,7&maxBuildsPerDefinition=1",
    "includeQueued": false,
    "showBuildStep": false
  }
}
```

The Tfs2015 service is deprecated and will be removed in future, cause it's not that flexible.

**Comment by gas421** [comment]
Thanks for the replies.
I have the domain in the credentials.
I tried already with Tfs service in the past but I was not able to generate the "pat" from TFS2015.
Is the pat available in TFS2015?

**Comment by marcells** [comment]
As I had written, in TFS 2015 PAT is your account password. Starting with TFS 2017 you have to create a PAT with special permissions for each use-case.

**Comment by Grifplex** [comment]
IT has upgraded our TFS to TFS2017 Update 3 RTM have tried this again from an Ubuntu system after installing node v8.11.1. When using Tfs2015 pugin I get a response of:
`TF400813: Resource not available for anonymous access. Client authentication required.`
using either password or pat and with Tfs plugin it crashes:
```
node-build-monitor is starting...
{ url: 'http://server:8080/tfs',
  collection: 'DefaultCollection',
  project: 'MyProjects',
  username: 'build',
  pat: 'my pat',
  queryparams: '',
  includeQueueud: 'true',
  showBuildStep: 'true' } '2.0'
08:30:33 | Check for builds...
node-build-monitor 0.9.44 is listening on port 3000...
no timeline url
08:30:35 | 260 builds found....
crypto.js:99
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at generateAndApplyETags (/home/build/node-build-monitor/app/monitor.js:14:18)
    at /home/build/node-build-monitor/app/monitor.js:172:13
    at /home/build/node-build-monitor/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/build/node-build-monitor/node_modules/async/dist/async.js:1050:13)
    at /home/build/node-build-monitor/node_modules/async/dist/async.js:958:16
    at /home/build/node-build-monitor/app/monitor.js:166:17
    at async.autoInject (/home/build/node-build-monitor/app/services/Tfs.js:225:7)
    at /home/build/node-build-monitor/node_modules/async/dist/async.js:473:16
    at processQueue (/home/build/node-build-monitor/node_modules/async/dist/async.js:1564:20)
```
or
```
node-build-monitor is starting...
{ url: 'http://server:8080/tfs',
  collection: 'DefaultCollection',
  project: 'MyProjects',
  username: 'build',
  pat: 'my pat',
  queryparams: '&$top=30',
  includeQueueud: 'true',
  showBuildStep: 'true' } '2.0'
08:37:16 | Check for builds...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/home/build/node-build-monitor/app/app.js:77:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```
or
```
build@UTP157-VM:~/node-build-monitor$ node app/app.js 
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = unset (Default: 1)
node-build-monitor is starting...
{ url: 'http://server:8080/tfs',
  collection: 'DefaultCollection',
  project: 'MyProjects',
  username: 'build',
  pat: 'my pat',
  queryparams: '',
  includeQueueud: 'false',
  showBuildStep: 'false' } '2.0'
08:48:58 | Check for builds...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/home/build/node-build-monitor/app/app.js:77:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by marcells** [comment]
Take a look at the [readme](https://github.com/marcells/node-build-monitor#team-foundation-server-20152017-on-premise):
> Important: For TFS 2017 you have to create a personal access token. It only needs the permission to read builds. Please use your username and the generated token as the password.

Use that [token](https://docs.microsoft.com/en-us/vsts/accounts/use-personal-access-tokens-to-authenticate?view=vsts) as the password.

**Comment by marcells** [comment]
In the last to code snippets there was an error `Error: listen EADDRINUSE :::3000`. That means, that the build-monitor was already started and the port in use.

**Comment by marcells** [comment]
Very strange. Could you try the `Tfs` (not `Tfs2015`) service? The[ configuration](https://github.com/marcells/node-build-monitor#visual-studio-team-services-and-team-foundation-server) is slightly different. The Tfs2015 plugin is deprecated and will be removed in future.

Please let me know, if it works for you.

**Comment by marcells** [comment]
Ah, okay. Could you try to inspect the requests/responses with [Fiddler](https://www.telerik.com/fiddler) or Wireshark? It's very strange, that you receive the number of builds, but no further information.

**Comment by Grifplex** [comment]
I am seeing an HTTP GET request for all 269 build definitions and responses following are proper JSON.

**Comment by Grifplex** [comment]
When using `"queryparams": "&$top=10"` instead of blank the following error occurs even though the initial query for builds and response contain valid JSON seen by WireShark.
```
build@UTP157-VM:~/node-build-monitor$ node app/app.js 
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = unset (Default: 1)
node-build-monitor is starting...
{ url: 'http://server:8080/tfs',
  collection: 'DefaultCollection',
  project: 'MyProjects',
  username: 'build',
  pat: 'my pat',
  queryparams: '&$top=10',
  includeQueueud: 'true',
  showBuildStep: 'true' } '2.0'
14:16:19 | Check for builds...
node-build-monitor 0.9.44 is listening on port 3000...
/home/build/node-build-monitor/app/services/Tfs.js:333
      options.url = `${url}/${collection}/${project}/_apis/build/builds?api-version=${apiVersion}&definitions=${def}&$top=2`;
      ^

ReferenceError: options is not defined
    at async.map (/home/build/node-build-monitor/app/services/Tfs.js:333:7)
    at /home/build/node-build-monitor/node_modules/async/dist/async.js:1121:9
    at eachOfArrayLike (/home/build/node-build-monitor/node_modules/async/dist/async.js:1055:9)
    at eachOf (/home/build/node-build-monitor/node_modules/async/dist/async.js:1103:5)
    at _asyncMap (/home/build/node-build-monitor/node_modules/async/dist/async.js:1119:5)
    at Object.map (/home/build/node-build-monitor/node_modules/async/dist/async.js:1108:16)
    at getPreviousBuilds (/home/build/node-build-monitor/app/services/Tfs.js:322:11)
    at get_previous_builds (/home/build/node-build-monitor/app/services/Tfs.js:201:9)
    at newTask (/home/build/node-build-monitor/node_modules/async/dist/async.js:2098:31)
    at runTask (/home/build/node-build-monitor/node_modules/async/dist/async.js:1618:13)
```

**Comment by marcells** [comment]
Hm, I have to check this issue by testing it on a on-premise instance. I will respond, when I find some time for it. Maybe this weekend or during the upcoming week.

**Comment by marcells** [comment]
I tried it on our production server right now and it worked as it should. I did use the following configuration:

```
    {
      "name": "Tfs",
      "configuration": {
        "url": "http://tfs-server:8080/tfs",
        "collection": "DefaultCollection",
        "project": "project",
        "username": "domain\\user",
        "pat": "123jh123kh123k12k3hk23...",
        "queryparams": "&$top=12",
        "includeQueued": true,
        "showBuildStep": true
      }
```

**Comment by marcells** [comment]
Could you post a sample of the data which is returned by rest call? I've no idea what's happening there.

**Comment by Grifplex** [comment]
[top30.txt](https://github.com/marcells/node-build-monitor/files/1996629/top30.txt)

**Comment by marcells** [comment]
I provided a fix right now for your issue. The builds could be mapped to the build monitor format and were visible now. But I did comment out all subsequent requests (`get_previous_build`, `merge_builds`, `get_build_steps`). So, it could be that there are some issues, too. Also try to set `showBuildStep` to false/true and see what's happening.

**Comment by marcells** [comment]
I made another update regarding the `options.url = ...` assignment issue you mentioned above.
https://github.com/marcells/node-build-monitor/releases/tag/v0.9.47

Please let me know, if the service is working for you now.

**Comment by Grifplex** [comment]
I have turned both `includeQueued` and `showBuildStep` to false. I'm still getting the `Data must be a string or a buffer` error:
```
build@UTP157-VM:~/node-build-monitor$ node app/app.js 
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = unset (Default: 1)
node-build-monitor is starting...
{ url: 'http://tfs-server:8080/tfs',
  collection: 'DefaultCollection',
  project: 'slm831c_app',
  username: 'pcb\\build',
  pat: 'my pat',
  queryparams: '&$top=12',
  includeQueueud: 'false',
  showBuildStep: 'false' } '2.0'
12:06:27 | Check for builds...
node-build-monitor 0.9.47 is listening on port 3000...
12:06:27 | 12 builds found....
12:06:27 | builds changed
12:06:42 | Check for builds...
12:06:42 | 12 builds found....
12:06:57 | Check for builds...
12:06:57 | 12 builds found....
12:07:12 | Check for builds...
12:07:13 | 12 builds found....
12:07:28 | Check for builds...
12:07:28 | 12 builds found....
12:07:43 | Check for builds...
12:07:43 | 12 builds found....
12:07:58 | Check for builds...
12:07:58 | 12 builds found....
12:08:13 | Check for builds...
12:08:14 | 12 builds found....
12:08:29 | Check for builds...
12:08:29 | 12 builds found....
12:08:44 | Check for builds...
12:08:44 | 12 builds found....
12:08:59 | Check for builds...
12:09:00 | 12 builds found....
12:09:15 | Check for builds...
12:09:15 | 12 builds found....
12:09:30 | Check for builds...
12:09:30 | 12 builds found....
12:09:45 | Check for builds...
12:10:20 | 12 builds found....
crypto.js:99
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at generateAndApplyETags (/home/build/node-build-monitor/app/monitor.js:14:18)
    at /home/build/node-build-monitor/app/monitor.js:172:13
    at /home/build/node-build-monitor/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/build/node-build-monitor/node_modules/async/dist/async.js:1050:13)
    at /home/build/node-build-monitor/node_modules/async/dist/async.js:958:16
    at /home/build/node-build-monitor/app/monitor.js:166:17
    at async.autoInject (/home/build/node-build-monitor/app/services/Tfs.js:225:7)
    at /home/build/node-build-monitor/node_modules/async/dist/async.js:473:16
    at processQueue (/home/build/node-build-monitor/node_modules/async/dist/async.js:1564:20)
```
