### ISSUE TITLE
Does it work with VSTS?

### ISSUE THREAD

**Issue by byatis** [marcells/node-build-monitor#87]
Hi!

It seems to me that node-build-monitor doesn't work with VSTS at all. Have I misunderstood something? It tries to get proxy settings when using TFS.js but as per instructions there aren't any. If  I change the TFS module to use direct url, it tries to use tfsodata.visualstudio.com which doesn't exists anymore.

Maybe this should be changed to use the REST API? 
https://stackoverflow.com/questions/37526062/tfs-odata-get-work-item-types

**Comment by marcells** [comment]
I have to check this. Thanks for the hint.

**Comment by byatis** [comment]
Hi! I forked this project and made VSTSRest simple plugin, you can see it here:
https://github.com/byatis/node-build-monitor

It works using Personal Access Tokens and you can define queries quite flexible. Not tested much yet though.

Feel free to merge it and develop further if you want. :)
