### ISSUE TITLE
TypeError: pipelines.slice is not a function

### ISSUE THREAD

**Issue by timaschew** [marcells/node-build-monitor#90]
I cloned the repo today and then configured with our GitLab server.
It worked for a couple of hours, but then I got this error:

```
/Users/wilhelm/dev/node-build-monitor/app/services/GitLab.js:46
                    pipelines = pipelines.slice(0, self.config.numberOfPipelinesPerProject);
                                          ^

TypeError: pipelines.slice is not a function
    at /Users/wilhelm/dev/node-build-monitor/app/services/GitLab.js:46:43
    at Request._callback (/Users/wilhelm/dev/node-build-monitor/app/services/GitLab.js:36:17)
    at Request.self.callback (/Users/wilhelm/dev/node-build-monitor/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/wilhelm/dev/node-build-monitor/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/wilhelm/dev/node-build-monitor/node_modules/request/request.js:1091:12)
```

**Comment by marcells** [comment]
Hm, do you have more information about the issue? Maybe some output, why pipelines is not an array.

@ntamas Do you have an idea?

**Comment by ntamas** [comment]
I suspect this might have been a temporary hiccup on GitLab's side and the API response was malformed. I can add a type check [here](https://github.com/marcells/node-build-monitor/blob/master/app/services/GitLab.js#L45) so we don't try slicing the `pipelines` array if it is not really an array. Would that be OK?

**Comment by marcells** [comment]
Yes, if the issue occurs due to a strange behavior of GitLab, then it's okay to implement it.

**Comment by timaschew** [comment]
> Hm, do you have more information about the issue? Maybe some output, why pipelines is not an array.

I don't know how to find out that out, is there a debug mode?

**Comment by ntamas** [comment]
> if the issue occurs due to a strange behavior of GitLab
It's hard to tell - the [API documentation](https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines) for the corresponding method does not tell whether the response is always an array, but judging from the example I thought it would be safe to assume so. Since this is clearly not the case, I think it's best if I just add that check. I'll file a PR soon.

**Comment by marcells** [comment]
A new version is on the way.
https://github.com/marcells/node-build-monitor/releases/tag/v0.9.32

Thank you, @ntamas.
