### ISSUE TITLE
Gitlab slugs - support for subgroups

### ISSUE THREAD

**Issue by mrMagicCod3r** [marcells/node-build-monitor#93]
Hi, first of all, great dashboard!
I'm testing it with Gitlab and Jenkins and noticed there is no simple way to filter "team" projects out of Gitlab.  We use subgroups and when I specify slug like "my-team-group/*" I end up with only direct group projects. Other, nested in subgroups of this group are not visible in dashoard. So I coded such support by myself.

I fixed it that way:

In Gitlab.js

I changed this line
```javascript
indexOfNamespace = matchers.indexOf(project.namespace.path + "/*"),
```
With that:
```javascript
function startsWithMatcher(matcher) {
    prefix = matcher.replace("/*","")
    return project.namespace.full_path.startsWith(prefix)
}

var indexOfNamespace = matchers.findIndex(startsWithMatcher),
```

So now "my-team-group/\*" will include all child subgroups folders. Also, it works for "my-team-group/my-more-specific-group/*" subgroups and so on.

What do you think? I know it's not backward compatible so I guess some config property for this will be nice.
If you find it worth adding but don't have time, I can prepare pull request.

EDIT:

You may also ask why didn't I just filter it out by additionalQuery. Well in gitlab each subgroup is a different group and search criteria only matches whole group name, no wildcards. So I can only filter by one group a time.

**Comment by marcells** [comment]
Hi,

thanks. Nice that you like it.

Yes, please make an optional configuration entry for this functionality and put it in the documentation, too.

I don't have a running GitLab instance where I could test it. So please make a PR.

Kind regards

**Comment by mrMagicCod3r** [comment]
After some thinking I have slightly different idea. Instead of additional property I can add support for double asterisk in slug wildcards. It will work unix-like, so /** will include projects from current and any nested groups while /* will remain the same - only current projects, no nesting. 

Quoting bash * manual:

>Matches any string, including the null string. When the globstar shell option is enabled, and `*` is used in a filename expansion context, two adjacent `*`s used as a single pattern will match all files and zero or more directories and subdirectories. If followed by a `/', two adjacent ``*'s will match only directories and subdirectories.
 

Here is my WIP code:

```javascript
function getNamespaceIndex(namespace) {
    for(matcher of matchers){
        if(matcher.endsWith("/**")){
            prefix = matcher.replace("/**","");
            if(namespace.full_path.startsWith(prefix)){
                return 0;
            }
        }else{
            if( matcher === namespace.full_path + "/*"){
                return 0;
            }
        }
    }
    return -1;
}
var indexOfNamespace = getNamespaceIndex(project.namespace),
``` 
What do you think? Also any feedback on my code is very welcomed as I'm new to js world.

**Comment by marcells** [comment]
Yes, as long as it works and produces no side effects with existing configurations the idea sounds good. ;-)
I don't know how the GitLab plugin works, cause the extension was not developed by me.

With `grunt ci` you can check the unit tests and if you violate against the coding style.

Just make a PR and I'll review it. ;-)
