### ISSUE TITLE
Hide Gitlab projects without gitlab-ci configuration

### ISSUE THREAD

**Issue by Kuipers** [marcells/node-build-monitor#97]
Hi, this build monitor does help us a lot!

We have Gitlab with a lot of repositories. And are moving to gitlab-ci builds. So not all projects have valid configurations to show. And not all projects will have one. 

Can we hide the projects which don't have a pipeline configuration when using */* to select all projects?
Now the projects without a pipeline configuration are shown gray with `<repro-name>/undefined`.

The workaround for now is to define every project in the slugs tag which gets a pipeline configuration. But this is pretty time consuming to maintain.

Maybe it's already possible but are we missing it. Or else I would like to propose this as a new feature. 

Keep up the good work!

**Comment by marcells** [comment]
@ntamas Do you know, if that os already possible? Or could that be implemented?

**Comment by ntamas** [comment]
Hmmm, I cannot really reproduce the issue on my side. Projects without a configured pipeline should simply not appear in the monitor at all.

@Kuipers Does this happen also when you specify a single project in the configuration file that is known _not_ to have a pipeline configuration, or does it happen only with wildcard matches?

**Comment by Kuipers** [comment]
This is the configuration which produces blocks like the image below:
![image](https://user-images.githubusercontent.com/1266198/34720850-9c813d58-f540-11e7-82f7-2c7bf6288019.png)

```
{
  "monitor":{
    "interval":30000,
    "numberOfBuilds":16,
    "latestBuildOnly":false,
    "sortOrder":"date",
    "debug":false
  },
  "services":[
    {
      "name":"GitLab",
      "configuration":{
        "url":"https://xxxxxxxxxxxxxxxxx",
        "token":"xxxxxxxxxxxxxxxx",
        "numberOfPipelinesPerProject":"1",
        "slugs":[
          {
            "project":"*/*"
          }
        ]
      }
    }
  ]
}
```
The project is hidden like you said if I add the warehouse project to the config file like this:
```
 "slugs":[
          {
            "project":"docker/robot-tester"
          },
          {
            "project":"Tools/warehouse"
          }
        ]
```

**Comment by ntamas** [comment]
Hmmm. Is it a self-hosted GitLab EE instance? I suspect that the API calls somehow behave differently from the GitLab instance at https://gitlab.com which I use for testing, but I cannot figure out how. Can you post the responses for the API requests fired at the following URLs:

* `/api/v4/projects/XXXXX/pipelines` for some project ID where there are configured CI jobs
* `/api/v4/projects/XXXXX/pipelines` for some project ID where there are no configured CI jobs

On GitLab, an API response for a project with a configured CI pipeline looks like [this](https://gitlab.com/api/v4/projects/5097061/pipelines), while an API response for a project with no pipelines is simply [an empty array](https://gitlab.com/api/v4/projects/5095802/pipelines). I suspect that this is not the case in your GitLab installation.

**Comment by Kuipers** [comment]
First of all thanks for the quick response!
We are using a self-hosted Gitlab-CE instance. 

Some version info:
```
node-build-monitor 0.9.35
GitLab 10.3.2
GitLab Shell 5.10.2
GitLab Workhorse v3.3.1
GitLab API v4
Gitaly 0.59.2
GitLab Pages 0.6.0
Git 2.14.3
Ruby 2.3.5p376
Rails 4.2.10
postgresql 9.6.5
```

Output of the project with a pipeline `/api/v4/projects/697/pipelines`:
```
[{"id":1252,"sha":"f5f53f12b848e40d957f1f1459177190cd03f5aa","ref":"develop","status":"success"},{"id":1251,"sha":"331d6f9ebb0767a4b5531b1bbf554e21dd6bc667","ref":"TRC-292","status":"success"},{"id":1250,"sha":"331d6f9ebb0767a4b5531b1bbf554e21dd6bc667","ref":"feature/TRC-292","status":"failed"},{"id":1104,"sha":"6f266fbd6d299c17d248222d182887807fc7cc4d","ref":"develop","status":"success"},{"id":1070,"sha":"7458d5c7336c85e0665c86bd36e3ac1565e20ead","ref":"TRC-202","status":"success"},{"id":1069,"sha":"f62a2d0c35c2b614919785554bb930cab36b2f25","ref":"TRC-202","status":"success"},{"id":1068,"sha":"1547e6fd02a3a20931e8ccc5ecc5a4d882dfc97d","ref":"TRC-202","status":"success"},{"id":1067,"sha":"9f473064b0bcda2b87f3e5999faa7c564e4d5c65","ref":"TRC-202","status":"success"},{"id":1044,"sha":"82f4ad0153ae406bf81333593ec32f7a8fd23bde","ref":"TRC-202","status":"success"}]
```

Output of the project without a pipeline `/api/v4/projects/693/pipelines`:
```
[]
```

It looks like the requests for the specific projects are OK than. But I don't know how to make this call for all projects with a wildcard `*/*`.

**Comment by ntamas** [comment]
Okay, so the only way I can reproduce an output similar to yours on my machine is when I deliberately "screw up" the pipeline IDs received for a project (e.g., by adding 1 to the pipeline ID after having retrieved the _real_ pipeline IDs from the project). This leads me to think that in your case, GitLab probably reports that the problematic projects _have_ some pipelines, but it is not possible to retrieve the details of the pipelines any more, maybe due to some kind of a cleanup process that happened in the meanwhile.

When I deliberately modify a pipeline ID for a project and try to retrieve a pipeline that does not exist, the GitLab API returns this:

```
{ message: "404 Not Found" }
```

which could in theory lead to the output that you see because none of the properties that we look for in the response are present so they end up as `undefined` in the object that holds the build properties to be shown on the UI.

I will add a patch for this soon but I'm not 100% sure that this will resolve your problem. I can post the patch here in advance so you can test it, and then I will send a pull request if it resolves your problem.

**Comment by ntamas** [comment]
Here is a patch that you can apply to `app/services/GitLab.js` - this improves the error handling so we do not freak out for pipeline IDs for which the details are not available any more:

```diff
diff --git a/app/services/GitLab.js b/app/services/GitLab.js
index 3246c55..5de273a 100644
--- a/app/services/GitLab.js
+++ b/app/services/GitLab.js
@@ -36,8 +36,18 @@ module.exports = function () {
                 callback(err, body);
             });
         },
+        makeRequestWithFallback = function (url, fallback, callback) {
+            request({
+                headers: getRequestHeaders(),
+                'url': url,
+                json: true
+            }, function(err, response, body) {
+                callback(err, response.statusCode != 200 ? fallback : body);
+            });
+        },
         getProjectPipelines = function(project, callback) {
-            makeRequest(buildProjectPipelinesUrl(project.id, project.ref), function(err, pipelines) {
+            var url = buildProjectPipelinesUrl(project.id, project.ref);
+            makeRequestWithFallback(url, [], function(err, pipelines) {
                 if(err) {
                     callback(err);
                     return;
@@ -47,19 +57,32 @@ module.exports = function () {
                 }
                 async.map(pipelines, function(pipeline, callback) {
                     getPipelineDetails(project, pipeline.id, callback);
-                }, callback);
+                }, function(err, pipelines) {
+                    if(err) {
+                        callback(err);
+                        return;
+                    } else {
+                        callback(null, pipelines.filter(function (id) { return id !== undefined; }));
+                    }
+                });
             });
         },
         getPipelineDetails = function(project, pipelineId, callback) {
             async.waterfall([
                 function(callback) {
-                    makeRequest(buildPipelineDetailsUrl(project.id, pipelineId), callback);
+                    var detailsUrl = buildPipelineDetailsUrl(project.id, pipelineId);
+                    makeRequestWithFallback(detailsUrl, undefined, callback);
                 },
                 function(pipeline, callback) {
-                    makeRequest(buildJobUrl(project.id, pipelineId), function(err, jobs) {
-                        pipeline.jobs = jobs;
-                        callback(err, simplifyBuild(project, pipeline));
-                    });
+                    if (pipeline !== undefined) {
+                        var url = buildJobUrl(project.id, pipelineId);
+                        makeRequestWithFallback(url, [], function(err, jobs) {
+                            pipeline.jobs = jobs;
+                            callback(err, simplifyBuild(project, pipeline));
+                        });
+                    } else {
+                        callback(null, undefined);
+                    }
                 }
             ], callback);
         },
```

**Comment by Kuipers** [comment]
Thanks for the patch @ntamas! I will try to apply it so I can test it. But that will be tomorrow before I get some time.

However I don't think the project reply contains some pipelines. 

The request for the specific pipelines with the id retrieved from the projects request is `[]`

How do you retrieve the pipelines? Is it by a wildcard or a walk over the json array retrieved by the projects request?

**Comment by ntamas** [comment]
Can you post the output of `/api/v4/projects/XXX/pipelines` for this particular project? (XXX should be the project ID).
